import type express from "express";
import { apiSecurityPolicy } from "./security.js";
import { registerAuthRoutes } from "./authRoutes.js";
import { registerPasswordResetRoutes, ensurePasswordResetIndexes } from "./passwordResetRoutes.js";
import { ensureAuthIndexes } from "./auth.js";
import { ensureLoginGuardIndexes } from "./loginGuard.js";
import { getMongoDb } from "./mongodb.js";
import { startSessionLifecycle } from "./sessionLifecycle.js";
import { startFnbLifecycle } from "./fnbLifecycle.js";
import { handleProductionGetStations, handleProductionAvailability, handleProductionCreateBooking } from "../services/productionBookingHandlers.js";
import { handleProductionAvailabilitySummary } from "../services/productionAvailabilitySummary.js";
import { handleProductionRescheduleBooking } from "../services/productionRescheduleHandler.js";
import { handleProductionCustomerBookings } from "../services/productionCustomerBookingsHandler.js";
import { handleProductionCheckInBooking, handleProductionCancelBooking, handleProductionExtendSession, handleProductionEndSession, handleProductionMyActiveSession } from "../services/productionSessionHandlers.js";
import { handleIssueBookingQr, handleEmployeeQrCheckIn, ensureQrCheckInIndexes } from "../services/productionQrCheckInHandlers.js";
import { handleProductionCreatePaymentOrder, handleProductionVerifyPayment } from "../services/productionPaymentHandlers.js";
import { handleProductionCreateInvoice, handleProductionWalletBalance, handleProductionWalletCredit, handleProductionWalletDebit, handleProductionRequestRefund } from "../services/productionBillingHandlers.js";
import { handleInvoicePdf } from "../services/productionInvoicePdfHandlers.js";
import { handleAdminProcessRefund, handleAdminCreditNote } from "../services/productionRefundHandlers.js";
import { handleAdminReconcileRefund } from "../services/productionRefundReconciliation.js";
import { employeeDashboard, getShift, startShift, endShift, cashLedger, addCashLedger, walkIn, checkIn, extendSession, transferSession, endSession, waitlist, addWaitlist, assignWaitlist, removeWaitlist, maintenance, reportMaintenance, updateMaintenance, alerts, resolveAlert, activity, refunds, requestRefund, processRefund, customers, createCustomer } from "../services/productionEmployeeHandlers.js";
import { handleEmployeeWalkInFinancial, handleEmployeeFnbFinancial, handleEmployeeEndSessionFinancial } from "../services/productionEmployeeFinancialHandlers.js";
import { registerAdminRoutes } from "../services/productionAdminHandlers.js";
import { handleMembershipMe, handlePurchaseMembership, handleConsumeMembershipHours } from "../services/productionMembershipHandlers.js";
import { handleCreateMembershipPaymentOrder } from "../services/productionMembershipPaymentHandlers.js";
import { handleAtomicVerifyMembershipPayment, handleAtomicMembershipWebhook } from "../services/productionMembershipAtomicPaymentHandlers.js";
import { handleFnbProducts, handleFnbOrderStatus } from "../services/productionFnbHandlers.js";
import { handleProductionCustomerFnbOrder, handleFnbPaymentOrder, handleFnbPaymentVerify, handleFnbCustomerRefund, handleAdminFnbRefund, handleAdminFnbCreditNote } from "../services/productionFnbFinancialHandlers.js";
import { handleAdminFinancialSummary, handleAdminFinancialLedger, handleAdminReconciliation, handleAdminFinancialExport } from "../services/productionFinancialHandlers.js";
import { handleTournamentList, handleTournamentDetail, handleTournamentRegister, handleTournamentPaymentOrder, handleAdminTournamentCreate, handleAdminTournamentUpdate, handleAdminTournamentTeams } from "../services/productionTournamentHandlers.js";
import { handleAtomicTournamentPaymentVerify } from "../services/productionTournamentAtomicPaymentHandlers.js";
import { handleTournamentFormResponse } from "../services/productionTournamentFormHandlers.js";
import { handleGoogleSheetsSync, handleAdminGameSyncPreview, handleGoogleSheetsPull, handleGoogleSheetsStatus } from "../services/productionGameSheetsHandlers.js";
import { handleProductionRazorpayPaymentWebhook, handleProductionRazorpayMembershipWebhook, handleProductionRazorpayFnbWebhook, handleProductionRazorpayTournamentWebhook } from "../services/productionRazorpayWebhookGateway.js";

export function registerProductionRoutes(app: express.Application): void {
  const get = (path: string, handler: express.RequestHandler) => app.get(path, apiSecurityPolicy, handler);
  const post = (path: string, handler: express.RequestHandler) => app.post(path, apiSecurityPolicy, handler);
  const patch = (path: string, handler: express.RequestHandler) => app.patch(path, apiSecurityPolicy, handler);
  const del = (path: string, handler: express.RequestHandler) => app.delete(path, apiSecurityPolicy, handler);

  get("/api/stations", handleProductionGetStations);
  get("/api/stations/:id/availability", handleProductionAvailability);
  get("/api/stations/:id/availability-summary", handleProductionAvailabilitySummary);
  post("/api/bookings", handleProductionCreateBooking);
  get("/api/bookings/me", handleProductionCustomerBookings);
  post("/api/bookings/:id/check-in", handleProductionCheckInBooking);
  post("/api/bookings/:id/qr", handleIssueBookingQr);
  post("/api/bookings/:id/cancel", handleProductionCancelBooking);
  post("/api/bookings/:id/reschedule", handleProductionRescheduleBooking);
  post("/api/sessions/:id/extend", handleProductionExtendSession);
  post("/api/sessions/:id/end", handleProductionEndSession);
  get("/api/sessions/me", handleProductionMyActiveSession);
  post("/api/payments/create-order", handleProductionCreatePaymentOrder);
  post("/api/payments/verify", handleProductionVerifyPayment);
  post("/api/payments/webhook", handleProductionRazorpayPaymentWebhook);
  post("/api/invoices", handleProductionCreateInvoice);
  get("/api/invoices/:id/pdf", handleInvoicePdf);
  get("/api/wallet/balance", handleProductionWalletBalance);
  post("/api/wallet/credit", handleProductionWalletCredit);
  post("/api/wallet/debit", handleProductionWalletDebit);
  post("/api/refunds", handleProductionRequestRefund);
  get("/api/membership", handleMembershipMe);
  get("/api/membership/me", handleMembershipMe);
  post("/api/membership/purchase", handlePurchaseMembership);
  post("/api/membership/consume", handleConsumeMembershipHours);
  post("/api/membership/payment-order", handleCreateMembershipPaymentOrder);
  post("/api/membership/payment-verify", handleAtomicVerifyMembershipPayment);
  post("/api/membership/payment-webhook", handleAtomicMembershipWebhook);
  get("/api/fnb/products", handleFnbProducts);
  get("/api/fnb/menu", handleFnbProducts);
  post("/api/fnb/orders", handleProductionCustomerFnbOrder);
  post("/api/fnb/order", handleProductionCustomerFnbOrder);
  post("/api/fnb/orders/:id/status", handleFnbOrderStatus);
  patch("/api/fnb/orders/:id/status", handleFnbOrderStatus);
  post("/api/fnb/payment-order", handleFnbPaymentOrder);
  post("/api/fnb/payment-verify", handleFnbPaymentVerify);
  post("/api/fnb/payment-webhook", handleProductionRazorpayFnbWebhook);
  post("/api/fnb/refunds", handleFnbCustomerRefund);
  get("/api/financial/summary", handleAdminFinancialSummary);
  get("/api/financial/ledger", handleAdminFinancialLedger);
  get("/api/financial/reconciliation", handleAdminReconciliation);
  get("/api/financial/export", handleAdminFinancialExport);
  get("/api/tournaments", handleTournamentList);
  get("/api/tournaments/:id", handleTournamentDetail);
  post("/api/tournaments/:id/register", handleTournamentRegister);
  post("/api/tournaments/payment-order", handleTournamentPaymentOrder);
  post("/api/tournaments/payment-verify", handleAtomicTournamentPaymentVerify);
  post("/api/tournaments/payment-webhook", handleProductionRazorpayTournamentWebhook);
  post("/api/admin/games/sheets/status", handleGoogleSheetsStatus);
  post("/api/admin/games/sheets/preview", handleAdminGameSyncPreview);
  post("/api/admin/games/sheets/sync", handleGoogleSheetsSync);
  post("/api/admin/games/sheets/pull", handleGoogleSheetsPull);
  get("/api/employee/dashboard", employeeDashboard);
  get("/api/employee/shift", getShift);
  post("/api/employee/shift/start", startShift);
  post("/api/employee/shift/end", endShift);
  get("/api/employee/cash-ledger", cashLedger);
  post("/api/employee/cash-ledger/entry", addCashLedger);
  post("/api/employee/walk-in", handleEmployeeWalkInFinancial);
  post("/api/employee/bookings/check-in", checkIn);
  post("/api/employee/check-in/qr", handleEmployeeQrCheckIn);
  post("/api/employee/sessions/:sessionId/extend", extendSession);
  post("/api/employee/sessions/:sessionId/transfer", transferSession);
  post("/api/employee/sessions/:sessionId/end", handleEmployeeEndSessionFinancial);
  get("/api/employee/waitlist", waitlist);
  post("/api/employee/waitlist/add", addWaitlist);
  post("/api/employee/waitlist/:waitlistId/assign", assignWaitlist);
  del("/api/employee/waitlist/:waitlistId", removeWaitlist);
  get("/api/employee/maintenance", maintenance);
  post("/api/employee/maintenance/report", reportMaintenance);
  post("/api/employee/maintenance/:ticketId/status", updateMaintenance);
  get("/api/employee/alerts", alerts);
  post("/api/employee/alerts/:alertId/resolve", resolveAlert);
  get("/api/employee/activity", activity);
  post("/api/employee/refunds/request", requestRefund);
  post("/api/employee/refunds/:refundId/action", processRefund);
  get("/api/employee/refunds", refunds);
  get("/api/employee/customers", customers);
  post("/api/employee/customers", createCustomer);
  post("/api/employee/fnb/order", handleEmployeeFnbFinancial);

  registerAuthRoutes(app);
  registerPasswordResetRoutes(app);
  registerAdminRoutes(app);
  post("/api/admin/refunds/:id/process", handleAdminProcessRefund);
  post("/api/admin/refunds/:id/reconcile", handleAdminReconcileRefund);
  post("/api/admin/refunds/:id/credit-note", handleAdminCreditNote);
  post("/api/admin/fnb-refunds/:id/process", handleAdminFnbRefund);
  post("/api/admin/fnb-refunds/:id/credit-note", handleAdminFnbCreditNote);
  post("/api/admin/tournaments", handleAdminTournamentCreate);
  patch("/api/admin/tournaments/:id", handleAdminTournamentUpdate);
  get("/api/admin/tournaments/:id/teams", handleAdminTournamentTeams);
  post("/api/integrations/google-sheets/sync", handleGoogleSheetsSync);
  post("/api/integrations/google-forms/tournament-response", handleTournamentFormResponse);

  app.get("/api/ready", async (_req, res) => {
    try { const db = await getMongoDb(); await db.command({ ping: 1 }); return res.json({ status: "ready", timestamp: new Date().toISOString(), dependencies: { mongodb: "ok" } }); }
    catch { return res.status(503).json({ status: "not_ready", timestamp: new Date().toISOString(), dependencies: { mongodb: "unavailable" } }); }
  });

  void ensureAuthIndexes().then(() => getMongoDb()).then(ensureLoginGuardIndexes).then(() => ensurePasswordResetIndexes()).then(() => ensureQrCheckInIndexes()).catch((error) => console.error("Authentication/index bootstrap failed:", error));
  startSessionLifecycle();
  startFnbLifecycle();
}

export function applyProductionPreload(app: express.Application): void {
  registerProductionRoutes(app);
}
