// @ts-nocheck
import { Request, Response } from 'express';
import {
  EmployeeShift, CashLedgerEntry, CashLedgerType, RefundRequest, RefundStatus, OperationalAlert,
  EmployeeActivity, EmployeeDashboardStats, EmployeeCustomerRecord, MaintenanceTicket,
  WaitlistEntry, ActiveSession, GamingSystem, Booking, Invoice, GamingServiceCategory
} from '../types';
import { getServerSystems, setServerSystems, getServerBookings, setServerBookings, getServerActiveSessions, setServerActiveSessions, getServerFnbOrders, setServerFnbOrders } from './apiHandlers';
import { INITIAL_FNB_PRODUCTS, INITIAL_PRICING_RULES } from '../data/initialData';

let currentShift: EmployeeShift = { id: 'shift-' + new Date().toISOString().slice(0, 10), employeeName: 'Staff (Dev / Lead)', shiftDate: new Date().toISOString().slice(0, 10), startTime: '09:00 AM', openingCash: 2500, cashSales: 840, upiSales: 1620, cardSales: 450, walletSales: 320, expenses: 150, status: 'OPEN' };
let cashLedger: CashLedgerEntry[] = [];
let operationalAlerts: OperationalAlert[] = [];
let maintenanceTickets: MaintenanceTicket[] = [];
let waitlistEntries: WaitlistEntry[] = [];
let refundRequests: RefundRequest[] = [];
let employeeActivityLog: EmployeeActivity[] = [];
let registeredCustomers: EmployeeCustomerRecord[] = [];
function logActivity(action: string, details: string, resource: string, employeeName = currentShift.employeeName) { employeeActivityLog.unshift({ id: 'act-' + Date.now(), employeeName, role: 'EMPLOYEE', action, details, resource, timestamp: 'Just now' }); if (employeeActivityLog.length > 50) employeeActivityLog.pop(); }

export function handleGetEmployeeDashboard(req: Request, res: Response) { const systems = getServerSystems(); const activeSessions = getServerActiveSessions(); const bookings = getServerBookings(); const stats: EmployeeDashboardStats = { activeSessionsCount: activeSessions.filter(s => s.status === 'ACTIVE').length, availableStationsCount: systems.filter(s => s.status === 'AVAILABLE').length, reservedStationsCount: systems.filter(s => s.status === 'RESERVED').length, maintenanceStationsCount: systems.filter(s => s.status === 'MAINTENANCE').length, upcomingBookingsCount: bookings.filter(b => b.bookingStatus === 'UPCOMING').length, waitlistCount: waitlistEntries.filter(w => w.status === 'WAITING').length, todayWalkInsCount: activeSessions.length, openFnbOrdersCount: getServerFnbOrders().filter(o => o.status !== 'DELIVERED').length, shiftCashCollected: currentShift.cashSales, shiftTotalRevenue: currentShift.cashSales + currentShift.upiSales + currentShift.cardSales + currentShift.walletSales, shiftStatus: currentShift.status }; const expectedCash = currentShift.openingCash + currentShift.cashSales - currentShift.expenses; return res.json({ success: true, data: { stats, shift: { ...currentShift, expectedCash, currentCashInDrawer: expectedCash }, recentAlerts: operationalAlerts.filter(a => !a.resolved).slice(0, 5), activeSessions: activeSessions.filter(s => s.status === 'ACTIVE'), systems } }); }
export function handleGetShiftStatus(req: Request, res: Response) { const expectedCash = currentShift.openingCash + currentShift.cashSales - currentShift.expenses; return res.json({ success: true, data: { shift: { ...currentShift, expectedCash, currentCashInDrawer: expectedCash }, ledger: cashLedger } }); }
export function handleStartShift(req: Request, res: Response) { const float = Number(req.body?.openingCash) || 0; const emp = req.body?.employeeName?.trim() || 'Front Desk Staff'; currentShift = { id: 'shift-' + Date.now(), employeeName: emp, shiftDate: new Date().toISOString().slice(0, 10), startTime: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), openingCash: float, cashSales: 0, upiSales: 0, cardSales: 0, walletSales: 0, expenses: 0, status: 'OPEN' }; return res.json({ success: true, message: `Shift started successfully for ${emp}.`, data: { shift: currentShift } }); }
export function handleEndShift(req: Request, res: Response) { const actual = Number(req.body?.actualCashCounted); if (!Number.isFinite(actual)) return res.status(400).json({ success: false, error: 'actualCashCounted is required.' }); const expectedCash = currentShift.openingCash + currentShift.cashSales - currentShift.expenses; currentShift.status = 'CLOSED'; currentShift.endTime = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); currentShift.closingCash = actual; currentShift.expectedCash = expectedCash; currentShift.difference = actual - expectedCash; return res.json({ success: true, data: { shift: currentShift, expectedCash, actualCash: actual, difference: actual - expectedCash, reconciled: actual === expectedCash } }); }
export function handleGetCashLedger(req: Request, res: Response) { return res.json({ success: true, data: { ledger: cashLedger, currentBalance: currentShift.openingCash + currentShift.cashSales - currentShift.expenses, shiftId: currentShift.id } }); }
export function handleAddCashLedgerEntry(req: Request, res: Response) { const amount = Number(req.body?.amount); if (!req.body?.type || !Number.isFinite(amount) || !req.body?.description) return res.status(400).json({ success: false, error: 'type, valid amount, and description are required.' }); const entry = { id: 'cld-' + Date.now(), shiftId: currentShift.id, type: req.body.type, amount, runningBalance: currentShift.openingCash + currentShift.cashSales - currentShift.expenses + amount, description: String(req.body.description).trim(), referenceId: req.body.referenceId, employeeName: currentShift.employeeName, timestamp: new Date().toISOString() } as CashLedgerEntry; cashLedger.unshift(entry); return res.json({ success: true, data: { entry, currentBalance: entry.runningBalance } }); }

export function handleEmployeeWalkIn(req: Request, res: Response) { const { systemId, customerName, customerPhone, durationHours, paymentMethod, useMembership, gameTitle, fnbItems } = req.body || {}; if (!systemId || !customerName || !customerPhone || !durationHours || !paymentMethod) return res.status(400).json({ success: false, error: 'systemId, customerName, customerPhone, durationHours, and paymentMethod are required.' }); const systems = getServerSystems(); const system = systems.find(s => s.id === systemId); if (!system) return res.status(404).json({ success: false, error: 'Station not found.' }); if (system.status !== 'AVAILABLE') return res.status(409).json({ success: false, error: `Station ${system.name} is currently ${system.status}.` }); const rule = INITIAL_PRICING_RULES.find(r => r.service === system.category); const hourlyRate = rule?.normalRate ?? system.hourlyRate ?? 250; const hours = Number(durationHours); if (!Number.isFinite(hours) || hours <= 0 || hours > 12) return res.status(400).json({ success: false, error: 'Invalid duration.' }); const gamingCharge = Math.round(hourlyRate * hours * (useMembership ? 0.8 : 1)); let fnbCharge = 0; if (Array.isArray(fnbItems)) for (const item of fnbItems) { const p = INITIAL_FNB_PRODUCTS.find(x => x.id === item.productId); if (p) fnbCharge += p.price * (item.quantity || 1); } const totalAmount = gamingCharge + fnbCharge; system.status = 'ACTIVE'; system.totalUsageHours += hours; system.totalRevenue += totalAmount; setServerSystems(systems); const now = new Date(); const end = new Date(now.getTime() + hours * 3600000); const newSession: any = { id: `sess-${Date.now()}`, systemId: system.id, systemName: system.name, customerName: customerName.trim(), customerPhone: customerPhone.trim(), gameTitle: gameTitle || 'Gaming Session', startTime: now.getTime(), endTime: end.getTime(), durationHours: hours, ratePerHour: hourlyRate, membershipUsedHours: useMembership ? hours : 0, vipMembershipUsedHours: 0, foodItems: fnbItems || [], foodTotal: fnbCharge, totalAmount, gamingCharge, fnbOrders: fnbItems || [], fnbTotalCharge: fnbCharge, totalCharge: totalAmount, status: 'ACTIVE', paymentMethod, employeeName: currentShift.employeeName, paymentStatus: 'PAID' }; const active = getServerActiveSessions(); active.unshift(newSession); setServerActiveSessions(active); if (paymentMethod === 'Cash') currentShift.cashSales += totalAmount; else if (paymentMethod === 'UPI') currentShift.upiSales += totalAmount; else if (paymentMethod === 'Card') currentShift.cardSales += totalAmount; else if (paymentMethod === 'Wallet') currentShift.walletSales += totalAmount; logActivity('WALKIN_SESSION', `Walk-in started on ${system.name} for ${hours}hr (₹${totalAmount})`, system.name); return res.json({ success: true, data: { session: newSession, system } }); }

export function handleEmployeeExtendSession(req: Request, res: Response) { const s = getServerActiveSessions().find(x => x.id === req.params.sessionId); const added = Number(req.body?.extraHours); if (!s || s.status !== 'ACTIVE' || !Number.isFinite(added) || added <= 0) return res.status(400).json({ success: false, error: 'Valid active session and extraHours required.' }); s.endTime = Number(s.endTime) + added * 3600000; s.durationHours += added; const system = getServerSystems().find(x => x.id === s.systemId); const rate = system?.hourlyRate || 250; const cost = Math.round(rate * added); s.totalAmount = (s.totalAmount || 0) + cost; s.totalCharge = (s.totalCharge || 0) + cost; s.gamingCharge = (s.gamingCharge || 0) + cost; if (req.body?.paymentMethod === 'Cash') currentShift.cashSales += cost; else if (req.body?.paymentMethod === 'UPI') currentShift.upiSales += cost; setServerActiveSessions(getServerActiveSessions()); return res.json({ success: true, data: { session: s } }); }
export function handleEmployeeTransferSession(req: Request, res: Response) { const sessions = getServerActiveSessions(); const s = sessions.find(x => x.id === req.params.sessionId); const systems = getServerSystems(); const target = systems.find(x => x.id === req.body?.targetSystemId); if (!s || s.status !== 'ACTIVE') return res.status(404).json({ success: false, error: 'Active session not found.' }); if (!target || target.status !== 'AVAILABLE') return res.status(409).json({ success: false, error: 'Target station unavailable.' }); const from = systems.find(x => x.id === s.systemId); if (from) from.status = 'AVAILABLE'; target.status = 'ACTIVE'; s.systemId = target.id; s.systemName = target.name; setServerSystems(systems); setServerActiveSessions(sessions); return res.json({ success: true, data: { session: s, fromSystem: from, toSystem: target } }); }
export function handleEmployeeEndSession(req: Request, res: Response) { const sessions = getServerActiveSessions(); const s: any = sessions.find(x => x.id === req.params.sessionId); if (!s) return res.status(404).json({ success: false, error: 'Session not found.' }); s.status = 'COMPLETED'; const systems = getServerSystems(); const system = systems.find(x => x.id === s.systemId); if (system) { system.status = 'AVAILABLE'; setServerSystems(systems); } setServerActiveSessions(sessions); return res.json({ success: true, data: { session: s } }); }
export function handleEmployeeBookingCheckIn(req: Request, res: Response) { const q = String(req.body?.bookingIdOrQr || '').trim().toUpperCase(); if (!q) return res.status(400).json({ success: false, error: 'bookingIdOrQr code is required.' }); const bookings = getServerBookings(); const b: any = bookings.find(x => x.id.toUpperCase() === q || String(x.qrCode || '').toUpperCase().includes(q) || String(x.qrCodePass || '').toUpperCase().includes(q)); if (!b) return res.status(404).json({ success: false, error: 'Reservation not found.' }); b.bookingStatus = 'ACTIVE'; const systems = getServerSystems(); const system = systems.find(x => x.id === b.systemId); if (!system || system.status === 'MAINTENANCE' || system.status === 'OFFLINE') return res.status(409).json({ success: false, error: 'Station unavailable.' }); system.status = 'ACTIVE'; setServerSystems(systems); setServerBookings(bookings); return res.json({ success: true, data: { booking: b, system } }); }

export function handleGetWaitlist(req: Request, res: Response) { return res.json({ success: true, data: waitlistEntries }); }
export function handleAddWaitlist(req: Request, res: Response) { const { customerName, customerPhone, service, durationHours, preferredTime } = req.body || {}; if (!customerName || !customerPhone || !service) return res.status(400).json({ success: false, error: 'customerName, customerPhone, and service are required.' }); const entry: any = { id: 'wait-' + Date.now(), customerName: String(customerName).trim(), customerPhone: String(customerPhone).trim(), service, durationHours: Number(durationHours) || 2, preferredTime: preferredTime || 'Next available', queuePosition: waitlistEntries.length + 1, status: 'WAITING', joinedAt: new Date().toISOString() }; waitlistEntries.push(entry); return res.json({ success: true, data: entry }); }
export function handleAssignWaitlistStation(req: Request, res: Response) { const e = waitlistEntries.find(x => x.id === req.params.waitlistId); if (!e) return res.status(404).json({ success: false, error: 'Waitlist entry not found.' }); e.status = 'CLAIMED'; return res.json({ success: true, data: e }); }
export function handleRemoveWaitlist(req: Request, res: Response) { const i = waitlistEntries.findIndex(x => x.id === req.params.waitlistId); if (i < 0) return res.status(404).json({ success: false, error: 'Waitlist entry not found.' }); return res.json({ success: true, data: waitlistEntries.splice(i, 1)[0] }); }
export function handleGetMaintenanceTickets(req: Request, res: Response) { return res.json({ success: true, data: maintenanceTickets }); }
export function handleCreateMaintenanceTicket(req: Request, res: Response) { const { systemId, issueCategory, severity, description, markMaintenance } = req.body || {}; if (!systemId || !description) return res.status(400).json({ success: false, error: 'systemId and description are required.' }); const system = getServerSystems().find(x => x.id === systemId); const ticket: any = { id: 'maint-' + Date.now(), systemId, systemName: system?.name || systemId, issueCategory: issueCategory || 'HARDWARE', severity: severity || 'MEDIUM', priority: severity || 'NORMAL', reportedBy: currentShift.employeeName, reportedAt: new Date().toISOString(), status: 'OPEN', description: String(description).trim() }; maintenanceTickets.unshift(ticket); if (markMaintenance && system) { system.status = 'MAINTENANCE'; setServerSystems(getServerSystems()); } return res.json({ success: true, data: ticket }); }
export function handleUpdateMaintenanceStatus(req: Request, res: Response) { const t: any = maintenanceTickets.find(x => x.id === req.params.ticketId); if (!t) return res.status(404).json({ success: false, error: 'Ticket not found.' }); if (req.body?.status) t.status = req.body.status; if (req.body?.resolutionNotes) t.resolutionNotes = req.body.resolutionNotes; if (t.status === 'RESOLVED') t.resolvedAt = new Date().toISOString(); if (req.body?.releaseStation && t.systemId) { const systems = getServerSystems(); const system = systems.find(x => x.id === t.systemId); if (system) { system.status = 'AVAILABLE'; setServerSystems(systems); } } return res.json({ success: true, data: t }); }
export function handleGetOperationalAlerts(req: Request, res: Response) { return res.json({ success: true, data: operationalAlerts }); }
export function handleResolveOperationalAlert(req: Request, res: Response) { const a = operationalAlerts.find(x => x.id === req.params.alertId); if (!a) return res.status(404).json({ success: false, error: 'Alert not found.' }); a.resolved = true; return res.json({ success: true, data: a }); }
export function handleGetEmployeeActivity(req: Request, res: Response) { return res.json({ success: true, data: employeeActivityLog }); }
export function handleGetRefundRequests(req: Request, res: Response) { return res.json({ success: true, data: refundRequests }); }
export function handleRequestRefund(req: Request, res: Response) { const { invoiceId, customerName, customerPhone, amount, reason } = req.body || {}; if (!invoiceId || !customerName || !amount || !reason) return res.status(400).json({ success: false, error: 'invoiceId, customerName, amount, and reason are required.' }); const ref: any = { id: 'ref-' + Date.now(), invoiceId, customerName, customerPhone: customerPhone || '', amount: Number(amount), reason: String(reason).trim(), requestedBy: currentShift.employeeName, status: 'REQUESTED', requestedAt: new Date().toISOString() }; refundRequests.unshift(ref); return res.json({ success: true, data: ref }); }
export function handleProcessRefund(req: Request, res: Response) { const ref: any = refundRequests.find(x => x.id === req.params.refundId); if (!ref) return res.status(404).json({ success: false, error: 'Refund request not found.' }); ref.status = req.body?.action === 'APPROVE' ? 'APPROVED' : 'REJECTED'; ref.processedAt = new Date().toISOString(); return res.json({ success: true, data: ref }); }
export function handleSearchCustomers(req: Request, res: Response) { const q = String(req.query?.q || '').trim().toLowerCase(); return res.json({ success: true, data: registeredCustomers.filter(c => !q || c.name.toLowerCase().includes(q) || c.phone.includes(q) || String(c.email || '').toLowerCase().includes(q) || String(c.gamerTag || '').toLowerCase().includes(q)).slice(0, 50) }); }
export function handleCreateCustomer(req: Request, res: Response) { const { name, phone, email, gamerTag } = req.body || {}; if (!name || !phone) return res.status(400).json({ success: false, error: 'name and phone are required.' }); const existing = registeredCustomers.find(c => c.phone.replace(/\D/g, '') === String(phone).replace(/\D/g, '')); if (existing) return res.json({ success: true, data: existing }); const c: any = { id: 'cust-' + Date.now(), name: String(name).trim(), phone: String(phone).trim(), email: email?.trim(), gamerTag: gamerTag?.trim() || String(name).replace(/\s+/g, ''), walletBalance: 0, totalVisits: 0, totalSpend: 0, lastVisit: 'First visit today', hasActiveSession: false }; registeredCustomers.unshift(c); return res.json({ success: true, data: c }); }
export function handleEmployeeFnbOrder(req: Request, res: Response) { const { items, sessionId, customerName, paymentMethod } = req.body || {}; if (!Array.isArray(items) || !items.length) return res.status(400).json({ success: false, error: 'items array is required.' }); let total = 0; for (const item of items) { const p = INITIAL_FNB_PRODUCTS.find(x => x.id === item.productId); if (p) total += p.price * (item.quantity || 1); } if (sessionId) { const sessions: any[] = getServerActiveSessions(); const s = sessions.find(x => x.id === sessionId); if (s) { s.fnbOrders = [...(s.fnbOrders || []), ...items]; s.fnbTotalCharge = (s.fnbTotalCharge || 0) + total; s.totalCharge = (s.totalCharge || 0) + total; setServerActiveSessions(sessions); } } if (paymentMethod === 'Cash') currentShift.cashSales += total; else if (paymentMethod === 'UPI') currentShift.upiSales += total; return res.json({ success: true, data: { total, items, sessionId } }); }
