import crypto from "node:crypto";
import type { Request, Response } from "express";
import type { AuthenticatedRequest } from "../server/auth.js";
import { getMongoDb } from "../server/mongodb.js";
import { writeAuditLog } from "../server/domainRepositories.js";
import { handleActivateMembership } from "./productionMembershipHandlers.js";

const BASE = "https://api.razorpay.com/v1";
function user(req: Request) { return (req as AuthenticatedRequest).user; }
function fail(res: Response, status: number, error: string) { return res.status(status).json({ success: false, error }); }
function env(name: string) { const v = process.env[name]?.trim(); if (!v) throw new Error(`${name}_NOT_CONFIGURED`); return v; }
function equal(a: string, b: string) { const aa = Buffer.from(a); const bb = Buffer.from(b); return aa.length === bb.length && crypto.timingSafeEqual(aa, bb); }
async function razor(path: string, init: RequestInit = {}) { const key = env("RAZORPAY_KEY_ID"), secret = env("RAZORPAY_KEY_SECRET"); const r = await fetch(`${BASE}${path}`, { ...init, headers: { "Content-Type": "application/json", Authorization: `Basic ${Buffer.from(`${key}:${secret}`).toString("base64")}`, ...(init.headers || {}) } }); const body = await r.json().catch(() => ({})); if (!r.ok) throw new Error("RAZORPAY_REQUEST_FAILED"); return body; }

export async function handleCreateMembershipPaymentOrder(req: Request, res: Response) {
  const u = user(req); if (!u) return fail(res, 401, "Authentication required");
  const membershipId = String(req.body?.membershipId || "").trim(); const key = String(req.header("Idempotency-Key") || req.body?.idempotencyKey || "").trim();
  if (!membershipId) return fail(res, 400, "membershipId is required"); if (key.length < 16 || key.length > 128) return fail(res, 400, "A valid Idempotency-Key is required");
  try { const db = await getMongoDb(); const membership = await db.collection("customer_memberships").findOne({ id: membershipId, customerId: u.id, status: "PENDING_PAYMENT", paymentStatus: "PENDING" }); if (!membership) return fail(res, 404, "Pending membership not found");
    const existing = await db.collection("payments").findOne({ customerId: u.id, membershipId, idempotencyKey: key }); if (existing?.providerOrderId) return res.json({ success: true, payment: existing, duplicate: true, razorpay: { keyId: env("RAZORPAY_KEY_ID"), orderId: existing.providerOrderId, amount: existing.amountPaise, currency: "INR" } });
    const order = await razor("/orders", { method: "POST", body: JSON.stringify({ amount: membership.pricePaise, currency: "INR", receipt: String(membership.id).slice(0, 40), notes: { membershipId: membership.id, customerId: u.id } }) });
    const now = new Date(); const payment = { id: `PAY-${Date.now()}-${crypto.randomBytes(5).toString("hex")}`, customerId: u.id, membershipId: membership.id, provider: "RAZORPAY", providerOrderId: order.id, amountPaise: membership.pricePaise, currency: "INR", status: "CREATED", idempotencyKey: key, createdAt: now, updatedAt: now };
    try { await db.collection("payments").insertOne(payment); } catch (e: any) { if (e?.code === 11000) { const dup = await db.collection("payments").findOne({ customerId: u.id, membershipId, idempotencyKey: key }); if (dup) return res.json({ success: true, payment: dup, duplicate: true, razorpay: { keyId: env("RAZORPAY_KEY_ID"), orderId: dup.providerOrderId, amount: dup.amountPaise, currency: "INR" } }); } throw e; }
    await writeAuditLog({ actorId: u.id, actorRole: u.role, action: "MEMBERSHIP_PAYMENT_ORDER_CREATED", entityType: "payment", entityId: payment.id, metadata: { membershipId, amountPaise: membership.pricePaise, providerOrderId: order.id } });
    return res.status(201).json({ success: true, payment, razorpay: { keyId: env("RAZORPAY_KEY_ID"), orderId: order.id, amount: membership.pricePaise, currency: "INR" } });
  } catch (e: any) { if (String(e.message).endsWith("_NOT_CONFIGURED")) return fail(res, 503, "Payment provider is not configured"); console.error("membership/payment-order", e); return fail(res, 502, "Unable to create membership payment order"); }
}

export async function handleVerifyMembershipPayment(req: Request, res: Response) {
  const u = user(req); if (!u) return fail(res, 401, "Authentication required"); const orderId = String(req.body?.razorpay_order_id || req.body?.orderId || "").trim(); const paymentId = String(req.body?.razorpay_payment_id || req.body?.paymentId || "").trim(); const supplied = String(req.body?.razorpay_signature || req.body?.signature || "").trim(); if (!orderId || !paymentId || !supplied) return fail(res, 400, "orderId, paymentId and signature are required");
  try { const secret = env("RAZORPAY_KEY_SECRET"); const expected = crypto.createHmac("sha256", secret).update(`${orderId}|${paymentId}`).digest("hex"); if (!equal(expected, supplied)) return fail(res, 400, "Invalid payment signature"); const db = await getMongoDb(); const payment = await db.collection("payments").findOne({ provider: "RAZORPAY", providerOrderId: orderId, customerId: u.id, membershipId: { $exists: true } }); if (!payment) return fail(res, 404, "Membership payment order not found"); if (payment.status === "CAPTURED") return res.json({ success: true, payment, membership: await db.collection("customer_memberships").findOne({ id: payment.membershipId }) , duplicate: true }); const provider = await razor(`/payments/${encodeURIComponent(paymentId)}`); if (String(provider.order_id) !== orderId || String(provider.currency) !== "INR" || Number(provider.amount) !== Number(payment.amountPaise)) return fail(res, 400, "Payment validation failed"); if (String(provider.status) !== "captured") return fail(res, 409, "Payment has not been captured"); const now = new Date(); const captured = await db.collection("payments").findOneAndUpdate({ _id: payment._id, status: { $ne: "CAPTURED" } }, { $set: { status: "CAPTURED", providerPaymentId: paymentId, providerStatus: provider.status, capturedAt: now, updatedAt: now } }, { returnDocument: "after" }); const finalPayment = captured || await db.collection("payments").findOne({ _id: payment._id }); const membership = await handleActivateMembership(String(payment.membershipId), String(finalPayment?.id), u.id, u.role); if (!membership) return fail(res, 409, "Membership is no longer awaiting payment"); await writeAuditLog({ actorId: u.id, actorRole: u.role, action: "MEMBERSHIP_PAYMENT_CAPTURED", entityType: "payment", entityId: payment.id, metadata: { membershipId: payment.membershipId, providerPaymentId: paymentId } }); return res.json({ success: true, payment: finalPayment, membership });
  } catch (e: any) { if (String(e.message).endsWith("_NOT_CONFIGURED")) return fail(res, 503, "Payment provider is not configured"); console.error("membership/payment-verify", e); return fail(res, 502, "Unable to verify membership payment"); }
}
