import crypto from "node:crypto";
import type { Request, Response } from "express";
import { ObjectId } from "mongodb";
import type { AuthenticatedRequest } from "../server/auth.js";
import { getMongoDb, getMongoClient } from "../server/mongodb.js";
import { writeAuditLog } from "../server/domainRepositories.js";

const BASE = "https://api.razorpay.com/v1";
const ENTRY_FEE_PAISE = 400000;
const MIN_MEMBERS = 4;
const MAX_MEMBERS = 10;
const fail = (res: Response, status: number, error: string) => res.status(status).json({ success: false, error });
const user = (req: Request) => (req as AuthenticatedRequest).user;
const id = (p: string) => `${p}-${Date.now()}-${crypto.randomBytes(5).toString("hex")}`;
const key = (req: Request) => String(req.header("Idempotency-Key") || req.body?.idempotencyKey || "").trim();
const validKey = (k: string) => k.length >= 16 && k.length <= 128;
const env = (n: string) => { const v = process.env[n]?.trim(); if (!v) throw new Error(`${n}_NOT_CONFIGURED`); return v; };
const safeEqual = (a: string, b: string) => { const x = Buffer.from(a), y = Buffer.from(b); return x.length === y.length && crypto.timingSafeEqual(x, y); };
async function razor(path: string, init: RequestInit = {}) { const auth = Buffer.from(`${env("RAZORPAY_KEY_ID")}:${env("RAZORPAY_KEY_SECRET")}`).toString("base64"); const r = await fetch(`${BASE}${path}`, { ...init, headers: { "Content-Type": "application/json", Authorization: `Basic ${auth}`, ...(init.headers || {}) } }); const body = await r.json().catch(() => ({})); if (!r.ok) throw new Error("RAZORPAY_REQUEST_FAILED"); return body; }
const findId = (v: string) => ObjectId.isValid(v) ? { $or: [{ id: v }, { _id: new ObjectId(v) }] } : { id: v };

function normalizeMembers(input: unknown) {
  if (!Array.isArray(input)) return [];
  return input.slice(0, MAX_MEMBERS).map((m: any, i) => ({ name: String(m?.name || "").trim().slice(0, 100), email: String(m?.email || "").trim().toLowerCase().slice(0, 160), phone: String(m?.phone || "").trim().slice(0, 30), gamerTag: String(m?.gamerTag || m?.username || "").trim().slice(0, 100), role: i === 0 ? "CAPTAIN" : "MEMBER" }));
}
function teamValid(members: any[]) { return members.length >= MIN_MEMBERS && members.every((m) => m.name && m.email); }

export async function handleTournamentList(req: Request, res: Response) {
  const db = await getMongoDb();
  const status = req.query.status ? String(req.query.status) : undefined;
  const filter: any = { ...(status ? { status } : {}) };
  return res.json({ success: true, data: await db.collection("tournaments").find(filter).sort({ startAt: 1 }).limit(100).toArray() });
}

export async function handleTournamentDetail(req: Request, res: Response) {
  const db = await getMongoDb(); const tournament = await db.collection("tournaments").findOne(findId(String(req.params.id || ""))); if (!tournament) return fail(res,404,"Tournament not found");
  return res.json({ success:true, data:{ ...tournament, entryFeePaise: Number(tournament.entryFeePaise ?? ENTRY_FEE_PAISE), minMembers: Number(tournament.minMembers ?? MIN_MEMBERS), maxMembers: Number(tournament.maxMembers ?? MAX_MEMBERS) } });
}

export async function handleTournamentRegister(req: Request, res: Response) {
  const u = user(req); if (!u) return fail(res,401,"Authentication required");
  const k = key(req); if (!validKey(k)) return fail(res,400,"A valid Idempotency-Key is required");
  const db = await getMongoDb(); const tournament = await db.collection("tournaments").findOne(findId(String(req.params.id || "")));
  if (!tournament) return fail(res,404,"Tournament not found");
  if (!["OPEN","REGISTRATION_OPEN","UPCOMING"].includes(String(tournament.status))) return fail(res,409,"Tournament registration is closed");
  const existing = await db.collection("tournament_teams").findOne({ tournamentId: String(tournament.id || tournament._id), captainId: u.id, registrationIdempotencyKey: k }); if (existing) return res.json({success:true,data:{team:existing},duplicate:true});
  const members = normalizeMembers(req.body?.members); if (!teamValid(members)) return fail(res,400,`A tournament team requires at least ${MIN_MEMBERS} members, including captain name and email`);
  const captain = members[0]; if (captain.email !== String(u.email || "").toLowerCase() && String(req.body?.captainEmail || "").toLowerCase() !== String(u.email || "").toLowerCase()) return fail(res,400,"The first team member must be the authenticated customer's email");
  const fee = Number(tournament.entryFeePaise ?? ENTRY_FEE_PAISE); if (!Number.isSafeInteger(fee) || fee !== ENTRY_FEE_PAISE) return fail(res,409,"Tournament entry fee must be ₹4,000");
  const now = new Date(); const team = { id:id("TEAM"), tournamentId:String(tournament.id || tournament._id), teamName:String(req.body?.teamName || "").trim().slice(0,100), captainId:u.id, members, memberCount:members.length, entryFeePaise:fee, paymentStatus:"PENDING", status:"PENDING_PAYMENT", registrationIdempotencyKey:k, googleFormUrl:String(tournament.googleFormUrl || ""), createdAt:now, updatedAt:now };
  if (!team.teamName) return fail(res,400,"teamName is required");
  if (members.length < Number(tournament.minMembers || MIN_MEMBERS)) return fail(res,400,`Minimum ${Number(tournament.minMembers || MIN_MEMBERS)} members are required`);
  try { await db.collection("tournament_teams").insertOne(team); } catch(e:any) { if(e?.code===11000)return fail(res,409,"Team registration already exists"); throw e; }
  await writeAuditLog({actorId:u.id,actorRole:u.role,action:"TOURNAMENT_TEAM_REGISTERED",entityType:"tournament_team",entityId:team.id,metadata:{tournamentId:team.tournamentId,memberCount:team.memberCount,entryFeePaise:fee}});
  return res.status(201).json({success:true,data:{team, googleFormUrl:team.googleFormUrl || null, paymentRequired:true}});
}

export async function handleTournamentPaymentOrder(req: Request,res: Response){
  const u=user(req);if(!u)return fail(res,401,"Authentication required");const k=key(req);if(!validKey(k))return fail(res,400,"A valid Idempotency-Key is required");const teamId=String(req.body?.teamId||"");if(!teamId)return fail(res,400,"teamId is required");
  try{const db=await getMongoDb();const team=await db.collection("tournament_teams").findOne({...findId(teamId),captainId:u.id});if(!team)return fail(res,404,"Tournament team not found");if(team.paymentStatus==="PAID")return res.json({success:true,data:{team},duplicate:true});const existing=await db.collection("payments").findOne({customerId:u.id,tournamentTeamId:team.id,idempotencyKey:k});if(existing?.providerOrderId)return res.json({success:true,data:{payment:existing},duplicate:true});const order=await razor("/orders",{method:"POST",body:JSON.stringify({amount:ENTRY_FEE_PAISE,currency:"INR",receipt:String(team.id).slice(0,40),notes:{tournamentTeamId:team.id,tournamentId:team.tournamentId,customerId:u.id}})});const payment={id:id("PAY"),customerId:u.id,tournamentTeamId:team.id,tournamentId:team.tournamentId,provider:"RAZORPAY",providerOrderId:order.id,amountPaise:ENTRY_FEE_PAISE,currency:"INR",status:"CREATED",idempotencyKey:k,createdAt:new Date(),updatedAt:new Date()};try{await db.collection("payments").insertOne(payment);}catch(e:any){if(e?.code===11000){const d=await db.collection("payments").findOne({customerId:u.id,tournamentTeamId:team.id,idempotencyKey:k});if(d)return res.json({success:true,data:{payment:d},duplicate:true});}throw e;}return res.status(201).json({success:true,data:{payment,razorpay:{keyId:env("RAZORPAY_KEY_ID"),orderId:order.id,amount:ENTRY_FEE_PAISE,currency:"INR"}}});}catch(e:any){if(e.message?.endsWith("_NOT_CONFIGURED"))return fail(res,503,"Payment provider is not configured");return fail(res,502,"Unable to create tournament payment order");}
}

async function captureTeamPayment(db:any,payment:any,providerPaymentId:string){const client=getMongoClient();if(!client)throw new Error("MONGO_TX_UNAVAILABLE");const s=client.startSession();try{await s.withTransaction(async()=>{const p=await db.collection("payments").findOne({_id:payment._id},{session:s});if(!p)throw new Error("PAYMENT_NOT_FOUND");const team=await db.collection("tournament_teams").findOne({id:p.tournamentTeamId},{session:s});if(!team)throw new Error("TEAM_NOT_FOUND");if(p.status==="CAPTURED")return;await db.collection("payments").updateOne({_id:p._id,status:{$ne:"CAPTURED"}},{$set:{status:"CAPTURED",providerPaymentId,capturedAt:new Date(),updatedAt:new Date()}},{session:s});await db.collection("tournament_teams").updateOne({id:team.id,paymentStatus:{$ne:"PAID"}},{$set:{paymentStatus:"PAID",status:"REGISTERED",paidAt:new Date(),paymentId:p.id,updatedAt:new Date()}},{session:s});});}finally{await s.endSession();}}

export async function handleTournamentPaymentVerify(req:Request,res:Response){const u=user(req);if(!u)return fail(res,401,"Authentication required");const teamId=String(req.body?.teamId||""),oid=String(req.body?.razorpay_order_id||""),pid=String(req.body?.razorpay_payment_id||""),sig=String(req.body?.razorpay_signature||"");if(!teamId||!oid||!pid||!sig)return fail(res,400,"Payment verification fields are required");try{const db=await getMongoDb();const payment=await db.collection("payments").findOne({customerId:u.id,tournamentTeamId:teamId,providerOrderId:oid});if(!payment)return fail(res,404,"Tournament payment not found");const expected=crypto.createHmac("sha256",env("RAZORPAY_KEY_SECRET")).update(`${oid}|${pid}`).digest("hex");if(!safeEqual(expected,sig))return fail(res,400,"Invalid payment signature");const provider=await razor(`/payments/${encodeURIComponent(pid)}`);if(provider.order_id!==oid||provider.currency!=="INR"||Number(provider.amount)!==ENTRY_FEE_PAISE)return fail(res,400,"Payment amount or order mismatch");if(provider.status!=="captured")return fail(res,409,"Payment has not been captured");await captureTeamPayment(db,payment,pid);const team=await db.collection("tournament_teams").findOne({id:teamId});return res.json({success:true,data:{team,payment:await db.collection("payments").findOne({_id:payment._id})}});}catch(e:any){if(e.message?.endsWith("_NOT_CONFIGURED"))return fail(res,503,"Payment provider is not configured");return fail(res,502,"Unable to verify tournament payment");}}

export async function handleTournamentPaymentWebhook(req:Request,res:Response){const signature=String(req.header("x-razorpay-signature")||"");if(!signature)return fail(res,400,"Webhook signature required");const secret=process.env.RAZORPAY_WEBHOOK_SECRET?.trim();if(!secret)return fail(res,503,"Webhook secret is not configured");const raw=Buffer.isBuffer((req as any).rawBody)?(req as any).rawBody:Buffer.from(JSON.stringify(req.body||{}));const expected=crypto.createHmac("sha256",secret).update(raw).digest("hex");if(!safeEqual(expected,signature))return fail(res,400,"Invalid webhook signature");const event=req.body||{};const entity=event?.payload?.payment?.entity;const eventKey=String(event?.id||`${event?.event}:${entity?.id||""}`);const db=await getMongoDb();try{await db.collection("razorpay_webhook_events").insertOne({key:`TOURNAMENT:${eventKey}`,event:event.event,receivedAt:new Date()});}catch(e:any){if(e?.code===11000)return res.json({success:true,duplicate:true});throw e;}if(event.event==="payment.captured"&&entity?.id){const payment=await db.collection("payments").findOne({provider:"RAZORPAY",providerPaymentId:entity.id});if(!payment&&entity.order_id)await db.collection("payments").updateOne({provider:"RAZORPAY",providerOrderId:entity.order_id},{$set:{providerPaymentId:entity.id,status:"CAPTURED",providerStatus:"captured",capturedAt:new Date(),updatedAt:new Date()}});const p=payment||await db.collection("payments").findOne({provider:"RAZORPAY",providerOrderId:entity.order_id});if(p?.tournamentTeamId)await captureTeamPayment(db,p,entity.id);}if(event.event==="payment.failed"&&entity?.order_id)await db.collection("payments").updateOne({provider:"RAZORPAY",providerOrderId:entity.order_id,status:{$ne:"CAPTURED"}},{$set:{status:"FAILED",providerPaymentId:entity.id,updatedAt:new Date()}});return res.json({success:true});}

export async function handleAdminTournamentCreate(req:Request,res:Response){const u=user(req);if(!u||!["ADMIN","SUPER_ADMIN"].includes(String(u.role)))return fail(res,403,"Admin access required");const b=req.body||{};const name=String(b.name||b.title||"").trim();if(!name)return fail(res,400,"Tournament name is required");const fee=Number(b.entryFeePaise??ENTRY_FEE_PAISE);const min=Number(b.minMembers??MIN_MEMBERS);const max=Number(b.maxMembers??MAX_MEMBERS);if(fee!==ENTRY_FEE_PAISE)return fail(res,400,"Tournament entry fee must be ₹4,000");if(!Number.isInteger(min)||min<MIN_MEMBERS)return fail(res,400,`Minimum team size cannot be below ${MIN_MEMBERS}`);if(!Number.isInteger(max)||max<min||max>MAX_MEMBERS)return fail(res,400,"Invalid maximum team size");const now=new Date();const doc={id:id("TOUR"),name,title:name,game:String(b.game||""),description:String(b.description||""),status:String(b.status||"DRAFT"),entryFeePaise:ENTRY_FEE_PAISE,minMembers:min,maxMembers:max,googleFormUrl:String(b.googleFormUrl||""),registrationClosesAt:b.registrationClosesAt?new Date(b.registrationClosesAt):null,startAt:b.startAt?new Date(b.startAt):null,endAt:b.endAt?new Date(b.endAt):null,prizePoolPaise:Number(b.prizePoolPaise||0),createdAt:now,updatedAt:now,createdBy:u.id};const db=await getMongoDb();await db.collection("tournaments").insertOne(doc);await writeAuditLog({actorId:u.id,actorRole:u.role,action:"ADMIN_TOURNAMENT_CREATE",entityType:"tournament",entityId:doc.id,metadata:{entryFeePaise:doc.entryFeePaise,minMembers:doc.minMembers,googleFormUrl:doc.googleFormUrl}});return res.status(201).json({success:true,data:doc});}

export async function handleAdminTournamentUpdate(req:Request,res:Response){const u=user(req);if(!u||!["ADMIN","SUPER_ADMIN"].includes(String(u.role)))return fail(res,403,"Admin access required");const db=await getMongoDb();const current=await db.collection("tournaments").findOne(findId(String(req.params.id||"")));if(!current)return fail(res,404,"Tournament not found");const b=req.body||{};const update:any={updatedAt:new Date()};for(const k of ["name","title","game","description","status","googleFormUrl","startAt","endAt","registrationClosesAt","prizePoolPaise"])if(b[k]!==undefined)update[k]=k.endsWith("At")||k==="registrationClosesAt"?(b[k]?new Date(b[k]):null):b[k];if(b.entryFeePaise!==undefined&&Number(b.entryFeePaise)!==ENTRY_FEE_PAISE)return fail(res,400,"Tournament entry fee must remain ₹4,000");if(b.minMembers!==undefined&&Number(b.minMembers)<MIN_MEMBERS)return fail(res,400,`Minimum team size cannot be below ${MIN_MEMBERS}`);if(b.maxMembers!==undefined&&(Number(b.maxMembers)>MAX_MEMBERS||Number(b.maxMembers)<Number(b.minMembers??current.minMembers??MIN_MEMBERS)))return fail(res,400,"Invalid maximum team size");if(b.minMembers!==undefined)update.minMembers=Number(b.minMembers);if(b.maxMembers!==undefined)update.maxMembers=Number(b.maxMembers);const result=await db.collection("tournaments").updateOne(findId(String(req.params.id||"")),{$set:update});await writeAuditLog({actorId:u.id,actorRole:u.role,action:"ADMIN_TOURNAMENT_UPDATE",entityType:"tournament",entityId:String(req.params.id),metadata:update});return res.json({success:true,data:await db.collection("tournaments").findOne(findId(String(req.params.id||"")))});}

export async function handleAdminTournamentTeams(req:Request,res:Response){const u=user(req);if(!u||!["ADMIN","SUPER_ADMIN"].includes(String(u.role)))return fail(res,403,"Admin access required");const db=await getMongoDb();const tournamentId=String(req.params.id||"");const teams=await db.collection("tournament_teams").find({tournamentId}).sort({createdAt:-1}).limit(500).toArray();return res.json({success:true,data:teams});}
