import crypto from "node:crypto";
import type { Request, Response } from "express";
import { ObjectId } from "mongodb";
import type { AuthenticatedRequest } from "../server/auth.js";
import { getMongoDb } from "../server/mongodb.js";
import { withTransaction, writeAuditLog } from "../server/domainRepositories.js";

const actor = (req: Request) => (req as AuthenticatedRequest).user;
const fail = (res: Response, code: number, error: string) => res.status(code).json({ success: false, error });
const makeId = (p: string) => `${p}-${Date.now()}-${crypto.randomBytes(5).toString("hex")}`;
const now = () => new Date();
const byId = (id: string) => ObjectId.isValid(id) ? { $or: [{ id }, { _id: new ObjectId(id) }] } : { id };
const employee = (req: Request) => actor(req)!;
const money = (v: unknown) => { const n = Number(v); return Number.isSafeInteger(n) && n >= 0 ? n : 0; };

async function audit(req: Request, action: string, type: string, id?: string, metadata?: Record<string, unknown>) {
  const u = actor(req); if (u) await writeAuditLog({ actorId: u.id, actorRole: u.role, action, entityType: type, entityId: id, metadata });
}

export async function employeeDashboard(req: Request, res: Response) {
  const db = await getMongoDb(); const day = new Date().toISOString().slice(0,10);
  const [active, available, reserved, maintenance, upcoming, wait, fnb, shift] = await Promise.all([
    db.collection("active_sessions").countDocuments({ status: "ACTIVE" }),
    db.collection("gaming_systems").countDocuments({ status: "AVAILABLE" }),
    db.collection("gaming_systems").countDocuments({ status: "RESERVED" }),
    db.collection("gaming_systems").countDocuments({ status: "MAINTENANCE" }),
    db.collection("bookings").countDocuments({ date: day, bookingStatus: "UPCOMING" }),
    db.collection("waitlist").countDocuments({ status: "WAITING" }),
    db.collection("fnb_orders").countDocuments({ status: { $nin: ["DELIVERED", "CANCELLED"] } }),
    db.collection("employee_shifts").findOne({ employeeId: employee(req).id, status: "OPEN" }),
  ]);
  const [sessions, systems, alerts] = await Promise.all([
    db.collection("active_sessions").find({ status: "ACTIVE" }).sort({ startedAt: -1 }).limit(50).toArray(),
    db.collection("gaming_systems").find({}).sort({ name: 1 }).toArray(),
    db.collection("audit_logs").find({ action: { $in: ["MAINTENANCE_REPORTED", "REFUND_REQUESTED", "SESSION_TRANSFERRED"] } }).sort({ createdAt: -1 }).limit(10).toArray(),
  ]);
  const shiftTotal = shift ? money(shift.cashSalesPaise)+money(shift.upiSalesPaise)+money(shift.cardSalesPaise)+money(shift.walletSalesPaise) : 0;
  return res.json({ success:true, data:{ stats:{activeSessionsCount:active,availableStationsCount:available,reservedStationsCount:reserved,maintenanceStationsCount:maintenance,upcomingBookingsCount:upcoming,waitlistCount:wait,todayWalkInsCount:sessions.length,openFnbOrdersCount:fnb,shiftCashCollectedPaise:shift?.cashSalesPaise||0,shiftTotalRevenuePaise:shiftTotal,shiftStatus:shift?.status||"CLOSED"}, shift, activeSessions:sessions, systems, recentAlerts:alerts } });
}

export async function getShift(req: Request,res:Response){ const db=await getMongoDb(); const s=await db.collection("employee_shifts").findOne({employeeId:employee(req).id,status:"OPEN"}); const ledger=s?await db.collection("cash_ledger").find({shiftId:s.id}).sort({createdAt:-1}).limit(500).toArray():[]; return res.json({success:true,data:{shift:s,ledger}}); }
export async function startShift(req:Request,res:Response){ const db=await getMongoDb(); const u=employee(req); const existing=await db.collection("employee_shifts").findOne({employeeId:u.id,status:"OPEN"}); if(existing)return fail(res,409,"An open shift already exists"); const opening=money(req.body?.openingCash); const s={id:makeId("SHIFT"),employeeId:u.id,employeeName:u.name||u.email||"Employee",shiftDate:new Date().toISOString().slice(0,10),startedAt:now(),openingCashPaise:opening,cashSalesPaise:0,upiSalesPaise:0,cardSalesPaise:0,walletSalesPaise:0,expensesPaise:0,status:"OPEN",createdAt:now(),updatedAt:now()}; await db.collection("employee_shifts").insertOne(s); await audit(req,"SHIFT_STARTED","employee_shift",s.id,{openingCashPaise:opening}); return res.status(201).json({success:true,data:{shift:s}}); }
export async function endShift(req:Request,res:Response){ const db=await getMongoDb(); const u=employee(req); const s:any=await db.collection("employee_shifts").findOne({employeeId:u.id,status:"OPEN"}); if(!s)return fail(res,404,"No open shift"); const actual=money(req.body?.actualCashCountedPaise ?? Number(req.body?.actualCashCounted||0)*100); const expected=money(s.openingCashPaise)+money(s.cashSalesPaise)-money(s.expensesPaise); const result=await db.collection("employee_shifts").findOneAndUpdate({id:s.id,status:"OPEN"},{$set:{status:"CLOSED",endedAt:now(),closingCashPaise:actual,expectedCashPaise:expected,differencePaise:actual-expected,updatedAt:now()}},{returnDocument:"after"}); await audit(req,"SHIFT_ENDED","employee_shift",s.id,{actualCashPaise:actual,expectedCashPaise:expected}); return res.json({success:true,data:{shift:result,expectedCashPaise:expected,actualCashPaise:actual,differencePaise:actual-expected,reconciled:actual===expected}}); }
export async function cashLedger(req:Request,res:Response){ const db=await getMongoDb(); const s:any=await db.collection("employee_shifts").findOne({employeeId:employee(req).id,status:"OPEN"}); if(!s)return res.json({success:true,data:{ledger:[],currentBalancePaise:0,shiftId:null}}); const ledger=await db.collection("cash_ledger").find({shiftId:s.id}).sort({createdAt:-1}).limit(500).toArray(); return res.json({success:true,data:{ledger,currentBalancePaise:money(s.openingCashPaise)+money(s.cashSalesPaise)-money(s.expensesPaise),shiftId:s.id}}); }
export async function addCashLedger(req:Request,res:Response){ const db=await getMongoDb(); const s:any=await db.collection("employee_shifts").findOne({employeeId:employee(req).id,status:"OPEN"}); if(!s)return fail(res,409,"Start a shift first"); const amount=money(req.body?.amountPaise ?? Number(req.body?.amount||0)*100); const type=String(req.body?.type||"").toUpperCase(); if(!amount||!type||!req.body?.description)return fail(res,400,"type, amount and description are required"); const entry={id:makeId("CASH"),shiftId:s.id,employeeId:employee(req).id,type,amountPaise:amount,description:String(req.body.description).slice(0,250),referenceId:req.body.referenceId,createdAt:now()}; await db.collection("cash_ledger").insertOne(entry); if(type.includes("EXPENSE"))await db.collection("employee_shifts").updateOne({id:s.id},{$inc:{expensesPaise:amount},$set:{updatedAt:now()}}); await audit(req,"CASH_LEDGER_ENTRY","cash_ledger",entry.id,{type,amountPaise:amount}); return res.status(201).json({success:true,data:{entry}}); }

export async function walkIn(req:Request,res:Response){ const db=await getMongoDb(); const {systemId,customerName,customerPhone,durationHours,paymentMethod,gameTitle}=req.body||{}; const hours=Number(durationHours); if(!systemId||!customerName||!customerPhone||!Number.isFinite(hours)||hours<=0||hours>12)return fail(res,400,"systemId, customerName, customerPhone and valid durationHours are required"); const result=await withTransaction(async(db,session)=>{ const system:any=await db.collection("gaming_systems").findOneAndUpdate({id:String(systemId),status:"AVAILABLE"},{$set:{status:"ACTIVE",updatedAt:now()}},{session,returnDocument:"after"}); if(!system)throw new Error("STATION_UNAVAILABLE"); const rule:any=await db.collection("pricing_rules").findOne({service:system.category}); const rate=money(rule?.normalRatePaise ?? (Number(rule?.normalRate||system.hourlyRate||0)*100)); const gaming=Math.round(rate*hours); const sessionDoc={id:makeId("SESS"),systemId:system.id,systemName:system.name,customerName:String(customerName).trim(),customerPhone:String(customerPhone).trim(),gameTitle:String(gameTitle||"Gaming Session"),startedAt:now(),scheduledEndAt:new Date(Date.now()+hours*3600000),durationHours:hours,ratePerHourPaise:rate,gamingChargePaise:gaming,totalPaise:gaming,paymentMethod:String(paymentMethod||"PENDING").toUpperCase(),paymentStatus:"PAID",status:"ACTIVE",employeeId:employee(req).id,createdAt:now(),updatedAt:now()}; await db.collection("active_sessions").insertOne(sessionDoc,{session}); return sessionDoc; }); if(!result)return fail(res,409,"Unable to start walk-in"); await audit(req,"WALKIN_SESSION_STARTED","active_session",result.id,{systemId}); return res.status(201).json({success:true,data:{session:result}}); }

export async function checkIn(req:Request,res:Response){ const db=await getMongoDb(); const id=String(req.body?.bookingIdOrQr||req.params.bookingId||"").trim(); if(!id)return fail(res,400,"bookingIdOrQr is required"); const booking:any=await db.collection("bookings").findOne({$or:[{id},{qrCode:id},{qrCodePass:id}]}); if(!booking)return fail(res,404,"Reservation not found"); if(booking.bookingStatus!=="UPCOMING")return fail(res,409,"Booking is not check-in eligible"); const result=await withTransaction(async(db,session)=>{ const station:any=await db.collection("gaming_systems").findOne({id:booking.systemId}); if(!station||["MAINTENANCE","OFFLINE","ACTIVE"].includes(station.status))throw new Error("STATION_UNAVAILABLE"); await db.collection("bookings").updateOne({id:booking.id,bookingStatus:"UPCOMING"},{$set:{bookingStatus:"ACTIVE",checkedInAt:now(),updatedAt:now()}},{session}); const s={id:makeId("SESS"),bookingId:booking.id,systemId:station.id,systemName:station.name,customerId:booking.customerId,customerName:booking.customerName,customerPhone:booking.customerPhone,startedAt:now(),scheduledEndAt:new Date(`${booking.date}T${booking.endTime}:00`),status:"ACTIVE",ratePerHourPaise:money(booking.ratePerHourPaise||Number(booking.hourlyRate||0)*100),totalPaise:money(booking.totalAmountPaise||Number(booking.totalAmount||0)*100),createdAt:now(),updatedAt:now(),employeeId:employee(req).id}; await db.collection("active_sessions").insertOne(s,{session}); await db.collection("gaming_systems").updateOne({id:station.id,status:station.status},{$set:{status:"ACTIVE",activeSessionId:s.id,updatedAt:now()}},{session}); return s; }); await audit(req,"BOOKING_CHECKED_IN","booking",booking.id,{sessionId:result.id}); return res.json({success:true,data:{bookingId:booking.id,session:result}}); }

export async function extendSession(req:Request,res:Response){ const db=await getMongoDb(); const id=req.params.sessionId; const extra=Number(req.body?.extraMinutes||0); if(!Number.isInteger(extra)||extra<30||extra>360||extra%30)return fail(res,400,"extraMinutes must be 30-360 in 30 minute increments"); const s:any=await db.collection("active_sessions").findOne({id,status:"ACTIVE"}); if(!s)return fail(res,404,"Active session not found"); const newEnd=new Date(new Date(s.scheduledEndAt).getTime()+extra*60000); const conflict=await db.collection("bookings").findOne({systemId:s.systemId,date:newEnd.toISOString().slice(0,10),bookingStatus:"UPCOMING",startTime:{$lt:newEnd.toISOString().slice(11,16)},endTime:{$gt:new Date(s.scheduledEndAt).toISOString().slice(11,16)}}); if(conflict)return fail(res,409,"Station has a conflicting booking"); const add=Math.round(money(s.ratePerHourPaise)*(extra/60)); const updated=await db.collection("active_sessions").findOneAndUpdate({id,status:"ACTIVE"},{$set:{scheduledEndAt:newEnd,updatedAt:now()},$inc:{totalPaise:add,gamingChargePaise:add}},{returnDocument:"after"}); await audit(req,"SESSION_EXTENDED","active_session",id,{extraMinutes:extra,addedPaise:add}); return res.json({success:true,data:{session:updated,addedPaise:add}}); }
export async function transferSession(req:Request,res:Response){ const db=await getMongoDb(); const id=req.params.sessionId,targetId=String(req.body?.targetSystemId||""); if(!targetId)return fail(res,400,"targetSystemId is required"); const result=await withTransaction(async(db,session)=>{ const s:any=await db.collection("active_sessions").findOne({id,status:"ACTIVE"},{session}); if(!s)throw new Error("SESSION_NOT_FOUND"); const target:any=await db.collection("gaming_systems").findOneAndUpdate({id:targetId,status:"AVAILABLE"},{$set:{status:"ACTIVE",activeSessionId:id,updatedAt:now()}},{session,returnDocument:"after"}); if(!target)throw new Error("TARGET_UNAVAILABLE"); await db.collection("gaming_systems").updateOne({id:s.systemId,status:"ACTIVE"},{$set:{status:"AVAILABLE",activeSessionId:null,updatedAt:now()}},{session}); const updated=await db.collection("active_sessions").findOneAndUpdate({id,status:"ACTIVE"},{$set:{systemId:target.id,systemName:target.name,updatedAt:now()}},{session,returnDocument:"after"}); return {updated,fromSystemId:s.systemId,toSystemId:target.id}; }); await audit(req,"SESSION_TRANSFERRED","active_session",id,{fromSystemId:result.fromSystemId,toSystemId:result.toSystemId}); return res.json({success:true,data:result}); }
export async function endSession(req:Request,res:Response){ const db=await getMongoDb(); const result=await withTransaction(async(db,session)=>{ const s:any=await db.collection("active_sessions").findOne({id:req.params.sessionId,status:"ACTIVE"},{session}); if(!s)throw new Error("SESSION_NOT_FOUND"); const ended=await db.collection("active_sessions").findOneAndUpdate({id:s.id,status:"ACTIVE"},{$set:{status:"COMPLETED",endedAt:now(),updatedAt:now()}},{session,returnDocument:"after"}); await db.collection("bookings").updateOne({id:s.bookingId,bookingStatus:"ACTIVE"},{$set:{bookingStatus:"COMPLETED",completedAt:now(),updatedAt:now()}},{session}); await db.collection("gaming_systems").updateOne({id:s.systemId},{$set:{status:"AVAILABLE",activeSessionId:null,updatedAt:now()}} ,{session}); return ended; }); await audit(req,"SESSION_ENDED","active_session",req.params.sessionId); return res.json({success:true,data:{session:result}}); }

export async function waitlist(req:Request,res:Response){ const db=await getMongoDb(); return res.json({success:true,data:await db.collection("waitlist").find({}).sort({joinedAt:1}).limit(500).toArray()}); }
export async function addWaitlist(req:Request,res:Response){ const {customerName,customerPhone,service,durationHours,preferredTime}=req.body||{}; if(!customerName||!customerPhone||!service)return fail(res,400,"customerName, customerPhone and service are required"); const db=await getMongoDb(); const doc={id:makeId("WAIT"),customerName:String(customerName).trim(),customerPhone:String(customerPhone).trim(),service,durationHours:Number(durationHours)||2,preferredTime:preferredTime||"Next available",status:"WAITING",joinedAt:now(),createdAt:now()}; doc["queuePosition"]=await db.collection("waitlist").countDocuments({status:"WAITING"})+1; await db.collection("waitlist").insertOne(doc); await audit(req,"WAITLIST_ADDED","waitlist",doc.id); return res.status(201).json({success:true,data:doc}); }
export async function assignWaitlist(req:Request,res:Response){ const db=await getMongoDb(); const stationId=String(req.body?.stationId||""); const result=await withTransaction(async(db,session)=>{ const e:any=await db.collection("waitlist").findOne({id:req.params.waitlistId,status:"WAITING"},{session}); if(!e)throw new Error("WAITLIST_NOT_FOUND"); if(stationId){const st=await db.collection("gaming_systems").findOne({id:stationId,status:"AVAILABLE"},{session});if(!st)throw new Error("STATION_UNAVAILABLE");} const updated=await db.collection("waitlist").findOneAndUpdate({id:e.id,status:"WAITING"},{$set:{status:"CLAIMED",assignedStationId:stationId||null,claimedAt:now(),updatedAt:now()}},{session,returnDocument:"after"}); return updated; }); return res.json({success:true,data:result}); }
export async function removeWaitlist(req:Request,res:Response){ const db=await getMongoDb(); const r=await db.collection("waitlist").findOneAndUpdate({id:req.params.waitlistId,status:"WAITING"},{$set:{status:"REMOVED",removedAt:now(),updatedAt:now()}},{returnDocument:"after"}); if(!r)return fail(res,404,"Waitlist entry not found"); return res.json({success:true,data:r}); }

export async function maintenance(req:Request,res:Response){ const db=await getMongoDb(); return res.json({success:true,data:await db.collection("maintenance_tickets").find({}).sort({createdAt:-1}).limit(500).toArray()}); }
export async function reportMaintenance(req:Request,res:Response){ const {systemId,issueCategory,priority,description,markMaintenance}=req.body||{}; if(!systemId||!description)return fail(res,400,"systemId and description are required"); const db=await getMongoDb(); const ticket={id:makeId("MAINT"),systemId,issueCategory:String(issueCategory||"HARDWARE"),priority:String(priority||"NORMAL"),description:String(description).slice(0,1000),reportedById:employee(req).id,reportedAt:now(),status:"OPEN",createdAt:now(),updatedAt:now()}; await db.collection("maintenance_tickets").insertOne(ticket); if(markMaintenance)await db.collection("gaming_systems").updateOne({id:systemId,status:{$nin:["ACTIVE","OFFLINE"]}},{$set:{status:"MAINTENANCE",updatedAt:now()}}); await audit(req,"MAINTENANCE_REPORTED","maintenance_ticket",ticket.id,{systemId}); return res.status(201).json({success:true,data:ticket}); }
export async function updateMaintenance(req:Request,res:Response){ const db=await getMongoDb(); const status=String(req.body?.status||"").toUpperCase(); if(!["OPEN","IN_PROGRESS","RESOLVED","CLOSED"].includes(status))return fail(res,400,"Invalid maintenance status"); const t:any=await db.collection("maintenance_tickets").findOne({id:req.params.ticketId}); if(!t)return fail(res,404,"Ticket not found"); const r=await db.collection("maintenance_tickets").findOneAndUpdate({id:t.id},{$set:{status,resolutionNotes:req.body?.resolutionNotes,updatedAt:now(),resolvedAt:status==="RESOLVED"||status==="CLOSED"?now():t.resolvedAt}},{returnDocument:"after"}); if((status==="RESOLVED"||status==="CLOSED")&&req.body?.releaseStation)await db.collection("gaming_systems").updateOne({id:t.systemId,status:"MAINTENANCE"},{$set:{status:"AVAILABLE",updatedAt:now()}}); await audit(req,"MAINTENANCE_STATUS_UPDATED","maintenance_ticket",t.id,{status}); return res.json({success:true,data:r}); }

export async function alerts(req:Request,res:Response){ const db=await getMongoDb(); const rows=await db.collection("audit_logs").find({action:{$in:["MAINTENANCE_REPORTED","REFUND_REQUESTED","PAYMENT_FAILED"]}}).sort({createdAt:-1}).limit(100).toArray(); return res.json({success:true,data:rows.map(x=>({...x,resolved:Boolean(x.resolved)}))}); }
export async function resolveAlert(req:Request,res:Response){ const db=await getMongoDb(); const r=await db.collection("audit_logs").findOneAndUpdate({_id:ObjectId.isValid(req.params.alertId)?new ObjectId(req.params.alertId):undefined},{$set:{resolved:true,resolvedAt:now(),resolvedById:employee(req).id}},{returnDocument:"after"}); if(!r)return fail(res,404,"Alert not found"); return res.json({success:true,data:r}); }
export async function activity(req:Request,res:Response){ const db=await getMongoDb(); return res.json({success:true,data:await db.collection("audit_logs").find({}).sort({createdAt:-1}).limit(500).toArray()}); }
export async function refunds(req:Request,res:Response){ const db=await getMongoDb(); return res.json({success:true,data:await db.collection("refunds").find({}).sort({createdAt:-1}).limit(500).toArray()}); }
export async function requestRefund(req:Request,res:Response){ const db=await getMongoDb(); const {invoiceId,bookingId,amountPaise,reason}=req.body||{}; const amount=money(amountPaise??Number(req.body?.amount||0)*100); if(!amount||(!invoiceId&&!bookingId))return fail(res,400,"invoiceId or bookingId and valid amount are required"); const doc={id:makeId("REF"),invoiceId,bookingId,amountPaise:amount,reason:String(reason||"Employee refund request").slice(0,250),status:"REQUESTED",requestedById:employee(req).id,createdAt:now(),updatedAt:now()}; await db.collection("refunds").insertOne(doc); await audit(req,"REFUND_REQUESTED","refund",doc.id,{amountPaise:amount}); return res.status(201).json({success:true,data:doc}); }
export async function processRefund(req:Request,res:Response){ const db=await getMongoDb(); const status=String(req.body?.status||"").toUpperCase(); if(!["APPROVED","REJECTED","PROCESSING","COMPLETED"].includes(status))return fail(res,400,"Invalid refund status"); const r:any=await db.collection("refunds").findOne({id:req.params.refundId}); if(!r)return fail(res,404,"Refund not found"); const updated=await db.collection("refunds").findOneAndUpdate({id:r.id,status:{$nin:["COMPLETED","REJECTED"]}},{$set:{status,processedById:employee(req).id,processedAt:now(),notes:req.body?.notes,updatedAt:now()}},{returnDocument:"after"}); await audit(req,"REFUND_STATUS_UPDATED","refund",r.id,{status}); return res.json({success:true,data:updated}); }
export async function customers(req:Request,res:Response){ const db=await getMongoDb(); const q=String(req.query?.q||"").trim(); const filter=q?{$or:[{name:{$regex:q,"$options":"i"}},{email:{$regex:q,"$options":"i"}},{phone:{$regex:q,"$options":"i"}}]}:{}; return res.json({success:true,data:await db.collection("users").find(filter,{projection:{passwordHash:0}}).limit(100).toArray()}); }
export async function createCustomer(req:Request,res:Response){ const db=await getMongoDb(); const name=String(req.body?.name||"").trim(),phone=String(req.body?.phone||"").trim(),email=String(req.body?.email||"").trim().toLowerCase(); if(!name||(!phone&&!email))return fail(res,400,"name and phone or email are required"); if(email&&await db.collection("users").findOne({email}))return fail(res,409,"Email already exists"); if(phone&&await db.collection("users").findOne({phone}))return fail(res,409,"Phone already exists"); const doc={id:makeId("USR"),name,phone:phone||undefined,email:email||undefined,role:"CUSTOMER",isActive:true,createdAt:now(),updatedAt:now()}; await db.collection("users").insertOne(doc); await audit(req,"CUSTOMER_CREATED","user",doc.id); return res.status(201).json({success:true,data:doc}); }
export async function fnbOrder(req:Request,res:Response){ const db=await getMongoDb(); const {customerId,items}=req.body||{}; if(!Array.isArray(items)||!items.length)return fail(res,400,"items are required"); const ids=items.map((x:any)=>String(x.productId||x.id||"")); const products=await db.collection("fnb_products").find({id:{$in:ids},isActive:{$ne:false}}).toArray(); let total=0; const lines=items.map((x:any)=>{const p:any=products.find((z:any)=>z.id===String(x.productId||x.id));const qty=Math.max(1,Math.min(100,Number(x.quantity)||1));const unit=money(p?.pricePaise??Number(p?.price||0)*100);total+=unit*qty;return {productId:p?.id||String(x.productId||x.id),name:p?.name||"Unknown",quantity:qty,unitPricePaise:unit,lineTotalPaise:unit*qty};}); const doc={id:makeId("FNB"),customerId:customerId||null,items:lines,totalPaise:total,status:"PLACED",orderedById:employee(req).id,createdAt:now(),updatedAt:now()}; await db.collection("fnb_orders").insertOne(doc); await audit(req,"FNB_ORDER_CREATED","fnb_order",doc.id,{totalPaise:total}); return res.status(201).json({success:true,data:doc}); }
