import crypto from "node:crypto";
import type { Request, Response } from "express";
import { ObjectId } from "mongodb";
import type { AuthenticatedRequest } from "../server/auth.js";
import { getMongoDb, getMongoClient } from "../server/mongodb.js";
import { writeAuditLog } from "../server/domainRepositories.js";

const BASE = "https://api.razorpay.com/v1";
const fail = (res: Response, status: number, error: string) => res.status(status).json({ success: false, error });
const actor = (req: Request) => (req as AuthenticatedRequest).user;
const makeId = (p: string) => `${p}-${Date.now()}-${crypto.randomBytes(5).toString("hex")}`;
const key = (req: Request) => String(req.header("Idempotency-Key") || req.body?.idempotencyKey || "").trim();
const money = (v: unknown) => { const n = Number(v); return Number.isSafeInteger(n) && n >= 0 ? n : 0; };
const env = (n: string) => { const v = process.env[n]?.trim(); if (!v) throw new Error(`${n}_NOT_CONFIGURED`); return v; };
const oidOrId = (id: string) => ObjectId.isValid(id) ? { $or: [{ id }, { _id: new ObjectId(id) }] } : { id };
const safeEqual = (a: string, b: string) => { const aa = Buffer.from(a); const bb = Buffer.from(b); return aa.length === bb.length && crypto.timingSafeEqual(aa, bb); };

async function razorpay(path: string, init: RequestInit = {}) {
  const auth = Buffer.from(`${env("RAZORPAY_KEY_ID")}:${env("RAZORPAY_KEY_SECRET")}`).toString("base64");
  const r = await fetch(`${BASE}${path}`, { ...init, headers: { "Content-Type": "application/json", Authorization: `Basic ${auth}`, ...(init.headers || {}) } });
  const body = await r.json().catch(() => ({}));
  if (!r.ok) { const e: any = new Error("RAZORPAY_REQUEST_FAILED"); e.provider = body; throw e; }
  return body;
}

async function invoiceForOrder(db: any, order: any, actorId: string, actorRole?: string) {
  const existing = await db.collection("invoices").findOne({ fnbOrderId: order.id, status: { $ne: "VOID" } });
  if (existing) return existing;
  const now = new Date();
  const invoice = {
    id: makeId("INV"), invoiceNumber: `BC-${now.getFullYear()}-${crypto.randomBytes(6).toString("hex").toUpperCase()}`,
    fnbOrderId: order.id, sourceBookingId: order.bookingId || null, sourceSessionId: order.sessionId || null,
    customerId: order.customerId || null, status: "ISSUED", paymentStatus: "PAID", currency: "INR",
    subtotalPaise: money(order.subtotalPaise), taxPaise: money(order.taxPaise), discountPaise: money(order.discountPaise), totalPaise: money(order.totalPaise),
    issuedAt: now, createdAt: now, updatedAt: now, immutable: true,
    items: (order.items || []).map((x: any) => ({ description: String(x.name || "F&B item"), quantity: Number(x.quantity), unitAmountPaise: money(x.unitPricePaise), amountPaise: money(x.amountPaise) }))
  };
  try { await db.collection("invoices").insertOne(invoice); } catch (e: any) { if (e?.code === 11000) return db.collection("invoices").findOne({ fnbOrderId: order.id }); throw e; }
  await writeAuditLog({ actorId, actorRole, action: "FNB_INVOICE_ISSUED", entityType: "invoice", entityId: invoice.id, metadata: { fnbOrderId: order.id, totalPaise: invoice.totalPaise } });
  return invoice;
}

async function releaseReservation(db: any, order: any, session: any) {
  for (const line of order.items || []) {
    await db.collection("fnb_products").updateOne({ $or: [{ id: line.productId }, ...(ObjectId.isValid(line.productId) ? [{ _id: new ObjectId(line.productId) }] : [])] }, { $inc: { reservedQty: -Number(line.quantity) }, $set: { updatedAt: new Date() } }, { session });
  }
}

async function captureReservation(db: any, order: any, session: any) {
  for (const line of order.items || []) {
    const r = await db.collection("fnb_products").updateOne({ $or: [{ id: line.productId }, ...(ObjectId.isValid(line.productId) ? [{ _id: new ObjectId(line.productId) }] : [])], reservedQty: { $gte: Number(line.quantity) }, stockQty: { $gte: Number(line.quantity) } }, { $inc: { reservedQty: -Number(line.quantity), stockQty: -Number(line.quantity) }, $set: { updatedAt: new Date() } }, { session });
    if (r.modifiedCount !== 1) throw new Error("RESERVATION_UNAVAILABLE");
  }
}

export async function handleProductionCustomerFnbOrder(req: Request, res: Response) {
  const u = actor(req); if (!u) return fail(res, 401, "Authentication required");
  const idempotencyKey = key(req); if (idempotencyKey.length < 16 || idempotencyKey.length > 128) return fail(res, 400, "A valid Idempotency-Key is required");
  const input = Array.isArray(req.body?.items) ? req.body.items : []; if (!input.length || input.length > 50) return fail(res, 400, "Invalid order items");
  const db = await getMongoDb(); const existing = await db.collection("fnb_orders").findOne({ customerId: u.id, idempotencyKey }); if (existing) return res.json({ success: true, data: { order: existing, invoice: existing.paymentStatus === "PAID" ? await invoiceForOrder(db, existing, u.id, u.role) : null }, duplicate: true });
  const paymentMethod = String(req.body?.paymentMethod || "UPI").toUpperCase(); if (!["UPI", "CARD", "WALLET"].includes(paymentMethod)) return fail(res, 400, "Customer F&B payment must be UPI, CARD or WALLET");
  const sessionId = req.body?.sessionId ? String(req.body.sessionId) : null; const bookingId = req.body?.bookingId ? String(req.body.bookingId) : null;
  if (sessionId && !(await db.collection("active_sessions").findOne({ id: sessionId, customerId: u.id, status: "ACTIVE" }))) return fail(res, 404, "Active gaming session not found");
  if (bookingId && !(await db.collection("bookings").findOne({ id: bookingId, customerId: u.id }))) return fail(res, 404, "Booking not found");
  const client = getMongoClient(); if (!client) return fail(res, 503, "MongoDB transaction support is unavailable");
  const tx = client.startSession(); let order: any;
  try {
    await tx.withTransaction(async () => {
      const normalized = input.map((x: any) => ({ productId: String(x?.productId || x?.id || "").trim(), quantity: Number(x?.quantity ?? x?.qty ?? 0), variant: x?.variant ? String(x.variant).slice(0, 100) : undefined }));
      if (normalized.some((x: any) => !x.productId || !Number.isInteger(x.quantity) || x.quantity < 1 || x.quantity > 50)) throw new Error("INVALID_ITEMS");
      const ids = [...new Set(normalized.map((x: any) => x.productId))];
      const products = await db.collection("fnb_products").find({ $or: ids.map(oidOrId), isActive: { $ne: false } }, { session: tx }).toArray();
      const byId = new Map(products.map((p: any) => [String(p.id || p._id), p])); if (products.length !== ids.length) throw new Error("PRODUCT_UNAVAILABLE");
      const lines: any[] = []; let subtotal = 0;
      for (const item of normalized) { const p: any = byId.get(item.productId); const unit = money(p?.pricePaise ?? Number(p?.price || 0) * 100); const stock = Number(p?.stockQty ?? 0); const reserved = Number(p?.reservedQty ?? 0); if (!unit) throw new Error("INVALID_PRICE"); if (stock - reserved < item.quantity) throw new Error("INSUFFICIENT_STOCK"); const amount = unit * item.quantity; subtotal += amount; lines.push({ productId: item.productId, name: String(p.name || p.title || "Item"), quantity: item.quantity, unitPricePaise: unit, amountPaise: amount, variant: item.variant }); }
      const taxPaise = money(req.body?.taxPaise); const discountPaise = Math.min(money(req.body?.discountPaise), subtotal + taxPaise); const totalPaise = subtotal + taxPaise - discountPaise; const now = new Date();
      order = { id: makeId("FNB"), customerId: u.id, customerName: u.name || u.email || null, sessionId, bookingId, items: lines, subtotalPaise: subtotal, taxPaise, discountPaise, totalPaise, currency: "INR", paymentMethod, paymentStatus: paymentMethod === "WALLET" ? "PAID" : "PENDING", status: "PLACED", idempotencyKey, inventoryStatus: paymentMethod === "WALLET" ? "CAPTURED" : "RESERVED", createdAt: now, updatedAt: now };
      if (paymentMethod === "WALLET") {
        const debit = await db.collection("wallet_accounts").updateOne({ customerId: u.id, balancePaise: { $gte: totalPaise } }, { $inc: { balancePaise: -totalPaise }, $set: { updatedAt: now } }, { session: tx }); if (debit.modifiedCount !== 1) throw new Error("INSUFFICIENT_WALLET_BALANCE");
        await db.collection("wallet_transactions").insertOne({ id: makeId("WT"), customerId: u.id, type: "DEBIT", source: "FNB_ORDER", amountPaise: totalPaise, currency: "INR", idempotencyKey: `FNB:${idempotencyKey}`, orderId: order.id, createdAt: now }, { session: tx });
      }
      await db.collection("fnb_orders").insertOne(order, { session: tx });
      for (const line of lines) {
        const filter: any = { $or: [{ id: line.productId }, ...(ObjectId.isValid(line.productId) ? [{ _id: new ObjectId(line.productId) }] : [])], isActive: { $ne: false } };
        if (paymentMethod === "WALLET") filter.$expr = { $gte: [{ $ifNull: ["$stockQty", 0] }, line.quantity] }; else filter.$expr = { $gte: [{ $subtract: [{ $ifNull: ["$stockQty", 0] }, { $ifNull: ["$reservedQty", 0] }] }, line.quantity] };
        const update: any = paymentMethod === "WALLET" ? { $inc: { stockQty: -line.quantity }, $set: { updatedAt: now } } : { $inc: { reservedQty: line.quantity }, $set: { updatedAt: now } };
        const r = await db.collection("fnb_products").updateOne(filter, update, { session: tx }); if (r.modifiedCount !== 1) throw new Error("INSUFFICIENT_STOCK");
      }
    });
  } catch (e: any) { if (e.message === "INVALID_ITEMS") return fail(res,400,"Invalid order items"); if (e.message === "PRODUCT_UNAVAILABLE") return fail(res,409,"One or more F&B items are unavailable"); if (e.message === "INVALID_PRICE") return fail(res,409,"One or more F&B prices are invalid"); if (e.message === "INSUFFICIENT_STOCK") return fail(res,409,"One or more F&B items are out of stock"); if (e.message === "INSUFFICIENT_WALLET_BALANCE") return fail(res,409,"Insufficient wallet balance"); console.error("fnb/customer-order",e); return fail(res,500,"Unable to create F&B order"); } finally { await tx.endSession(); }
  const invoice = order.paymentStatus === "PAID" ? await invoiceForOrder(db, order, u.id, u.role) : null; await writeAuditLog({ actorId:u.id, actorRole:u.role, action:"FNB_ORDER_CREATED", entityType:"fnb_order", entityId:order.id, metadata:{paymentMethod,totalPaise:order.totalPaise} }); return res.status(201).json({ success:true, data:{ order, invoice } });
}

export async function handleFnbPaymentOrder(req: Request, res: Response) {
  const u = actor(req); if (!u) return fail(res,401,"Authentication required"); const orderId = String(req.body?.orderId || "").trim(); const idempotencyKey = key(req); if (!orderId) return fail(res,400,"orderId is required"); if (idempotencyKey.length < 16 || idempotencyKey.length > 128) return fail(res,400,"A valid Idempotency-Key is required");
  try { const db = await getMongoDb(); const order = await db.collection("fnb_orders").findOne({ id: orderId, customerId: u.id }); if (!order) return fail(res,404,"F&B order not found"); if (order.paymentStatus === "PAID") return res.json({success:true,order,duplicate:true}); if (!["UPI","CARD"].includes(String(order.paymentMethod))) return fail(res,409,"Order is not an online payment order"); const existing = await db.collection("payments").findOne({ customerId:u.id, fnbOrderId:order.id, idempotencyKey }); if (existing?.providerOrderId) return res.json({success:true,payment:existing,duplicate:true}); const providerOrder = await razorpay("/orders",{method:"POST",body:JSON.stringify({amount:Number(order.totalPaise),currency:"INR",receipt:String(order.id).slice(0,40),notes:{fnbOrderId:order.id,customerId:u.id}})}); const now=new Date(); const payment={id:makeId("PAY"),customerId:u.id,fnbOrderId:order.id,provider:"RAZORPAY",providerOrderId:providerOrder.id,amountPaise:Number(order.totalPaise),currency:"INR",status:"CREATED",idempotencyKey,createdAt:now,updatedAt:now}; try{await db.collection("payments").insertOne(payment);}catch(e:any){if(e?.code===11000){const d=await db.collection("payments").findOne({customerId:u.id,fnbOrderId:order.id,idempotencyKey});if(d)return res.json({success:true,payment:d,duplicate:true});}throw e;} return res.status(201).json({success:true,payment,razorpay:{keyId:env("RAZORPAY_KEY_ID"),orderId:providerOrder.id,amount:Number(order.totalPaise),currency:"INR"}}); } catch(e:any){if(e.message?.endsWith("_NOT_CONFIGURED"))return fail(res,503,"Payment provider is not configured"); console.error("fnb/payment-order",e); return fail(res,502,"Unable to create F&B payment order");}
}

async function captureFnbPayment(db:any,payment:any,providerPaymentId:string,status:string){
  const client=getMongoClient(); if(!client) throw new Error("MONGO_TX_UNAVAILABLE"); const tx=client.startSession(); let order:any;
  try{await tx.withTransaction(async()=>{ const fresh=await db.collection("payments").findOne({_id:payment._id},{session:tx}); if(!fresh)throw new Error("PAYMENT_NOT_FOUND"); order=await db.collection("fnb_orders").findOne({id:fresh.fnbOrderId},{session:tx}); if(!order)throw new Error("FNB_ORDER_NOT_FOUND"); if(fresh.status==="CAPTURED")return; await db.collection("payments").updateOne({_id:fresh._id,status:{$ne:"CAPTURED"}},{$set:{status:"CAPTURED",providerPaymentId,providerStatus:status,capturedAt:new Date(),updatedAt:new Date()}},{session:tx}); await captureReservation(db,order,tx); await db.collection("fnb_orders").updateOne({id:order.id,paymentStatus:{$ne:"PAID"}},{$set:{paymentStatus:"PAID",inventoryStatus:"CAPTURED",paidAt:new Date(),paymentId:fresh.id,updatedAt:new Date()}},{session:tx}); });}finally{await tx.endSession();}
  return order;
}

export async function handleFnbPaymentVerify(req: Request,res: Response){const u=actor(req);if(!u)return fail(res,401,"Authentication required");const orderId=String(req.body?.orderId||"").trim(),orderPaymentId=String(req.body?.razorpay_payment_id||req.body?.paymentId||"").trim(),orderProviderId=String(req.body?.razorpay_order_id||req.body?.orderIdProvider||"").trim(),sig=String(req.body?.razorpay_signature||req.body?.signature||"").trim();if(!orderId||!orderPaymentId||!orderProviderId||!sig)return fail(res,400,"orderId, provider order, payment and signature are required");try{const secret=env("RAZORPAY_KEY_SECRET");const expected=crypto.createHmac("sha256",secret).update(`${orderProviderId}|${orderPaymentId}`).digest("hex");if(!safeEqual(expected,sig))return fail(res,400,"Invalid payment signature");const db=await getMongoDb();const payment=await db.collection("payments").findOne({provider:"RAZORPAY",providerOrderId:orderProviderId,fnbOrderId:orderId,customerId:u.id});if(!payment)return fail(res,404,"F&B payment order not found");if(payment.status==="CAPTURED")return res.json({success:true,payment,invoice:await db.collection("invoices").findOne({fnbOrderId:orderId}),duplicate:true});const p=await razorpay(`/payments/${encodeURIComponent(orderPaymentId)}`);if(String(p.order_id)!==orderProviderId||String(p.currency)!=="INR"||Number(p.amount)!==Number(payment.amountPaise))return fail(res,400,"Payment validation failed");if(String(p.status)!=="captured")return fail(res,409,"Payment has not been captured");const order=await captureFnbPayment(db,payment,orderPaymentId,String(p.status));const invoice=await invoiceForOrder(db,order,u.id,u.role);await writeAuditLog({actorId:u.id,actorRole:u.role,action:"FNB_PAYMENT_CAPTURED",entityType:"payment",entityId:payment.id,metadata:{fnbOrderId:orderId,providerPaymentId:orderPaymentId}});return res.json({success:true,payment:await db.collection("payments").findOne({_id:payment._id}),invoice});}catch(e:any){if(e.message?.endsWith("_NOT_CONFIGURED"))return fail(res,503,"Payment provider is not configured");if(e.message==="RESERVATION_UNAVAILABLE")return fail(res,409,"Reserved F&B stock is no longer available");console.error("fnb/payment-verify",e);return fail(res,502,"Unable to verify F&B payment");}}

export async function handleFnbPaymentWebhook(req:Request,res:Response){try{const secret=env("RAZORPAY_WEBHOOK_SECRET"),raw=(req as any).rawBody as Buffer|undefined,sig=req.header("X-Razorpay-Signature")||"";if(!raw?.length)return fail(res,400,"Missing raw webhook body");const expected=crypto.createHmac("sha256",secret).update(raw).digest("hex");if(!safeEqual(expected,sig))return fail(res,400,"Invalid webhook signature");const event=String(req.body?.event||""),entity=req.body?.payload?.payment?.entity;if(!entity?.id||!entity?.order_id)return res.json({success:true,ignored:true});const db=await getMongoDb(),keyValue=String(req.body?.id||`${event}:${entity.id}:${entity.order_id}`).slice(0,250);try{await db.collection("razorpay_webhook_events").insertOne({key:keyValue,event,paymentId:entity.id,orderId:entity.order_id,receivedAt:new Date()});}catch(e:any){if(e?.code===11000)return res.json({success:true,duplicate:true});throw e;}const payment=await db.collection("payments").findOne({provider:"RAZORPAY",providerOrderId:entity.order_id,fnbOrderId:{$exists:true}});if(!payment)return res.json({success:true,processed:false});if(Number(entity.amount)!==Number(payment.amountPaise)||String(entity.currency)!=="INR")return fail(res,400,"Webhook payment amount or currency mismatch");if(event==="payment.captured"){const order=await captureFnbPayment(db,payment,String(entity.id),String(entity.status||"captured"));const invoice=await invoiceForOrder(db,order,payment.customerId);return res.json({success:true,processed:true,invoiceId:invoice.id});}if(event==="payment.failed"){await db.collection("payments").updateOne({_id:payment._id,status:{$ne:"CAPTURED"}},{$set:{status:"FAILED",providerPaymentId:entity.id,providerStatus:entity.status,updatedAt:new Date()}});const order=await db.collection("fnb_orders").findOne({id:payment.fnbOrderId});if(order?.paymentStatus!=="PAID"&&order?.inventoryStatus==="RESERVED"){const tx=getMongoClient()!.startSession();try{await tx.withTransaction(async()=>{await releaseReservation(db,order,tx);await db.collection("fnb_orders").updateOne({id:order.id,paymentStatus:{$ne:"PAID"}},{$set:{paymentStatus:"FAILED",inventoryStatus:"RELEASED",status:"CANCELLED",updatedAt:new Date()}},{session:tx});});}finally{await tx.endSession();}}return res.json({success:true,processed:true});}return res.json({success:true,processed:true,ignoredEvent:event});}catch(e:any){if(e.message?.endsWith("_NOT_CONFIGURED"))return fail(res,503,"Webhook is not configured");console.error("fnb/payment-webhook",e);return fail(res,500,"Webhook processing failed");}}

export async function handleFnbCustomerRefund(req:Request,res:Response){const u=actor(req);if(!u)return fail(res,401,"Authentication required");const orderId=String(req.body?.orderId||"").trim(),amount=money(req.body?.amountPaise);if(!orderId||!amount)return fail(res,400,"orderId and amountPaise are required");const db=await getMongoDb(),order=await db.collection("fnb_orders").findOne({id:orderId,customerId:u.id,paymentStatus:"PAID"});if(!order)return fail(res,404,"Paid F&B order not found");if(amount>Number(order.totalPaise))return fail(res,400,"Refund exceeds order amount");const payment=await db.collection("payments").findOne({fnbOrderId:order.id,status:"CAPTURED",providerPaymentId:{$exists:true}});if(!payment)return fail(res,409,"No captured online payment is linked to this order");const existing=await db.collection("refunds").findOne({fnbOrderId:order.id,status:{$in:["REQUESTED","APPROVED","PROCESSING","COMPLETED"]}});if(existing)return res.json({success:true,refund:existing,duplicate:true});const refund={id:makeId("REF"),fnbOrderId:order.id,customerId:u.id,paymentId:payment.id,amountPaise:amount,currency:"INR",reason:String(req.body?.reason||"Customer F&B refund request").slice(0,250),status:"REQUESTED",createdAt:new Date(),updatedAt:new Date()};await db.collection("refunds").insertOne(refund);await writeAuditLog({actorId:u.id,actorRole:u.role,action:"FNB_REFUND_REQUESTED",entityType:"refund",entityId:refund.id,metadata:{fnbOrderId:order.id,amountPaise:amount}});return res.status(201).json({success:true,refund});}

export async function handleAdminFnbRefund(req:Request,res:Response){const u=actor(req);if(!u||!["ADMIN","SUPER_ADMIN"].includes(String(u.role)))return fail(res,403,"Admin access required");const id=String(req.params.id||"").trim(),action=String(req.body?.action||"").toUpperCase(),db=await getMongoDb(),refund=await db.collection("refunds").findOne({$or:[{id},...(ObjectId.isValid(id)?[{_id:new ObjectId(id)}]:[])]});if(!refund||!refund.fnbOrderId)return fail(res,404,"F&B refund not found");if(action==="REJECT"){if(!["REQUESTED","APPROVED"].includes(refund.status))return fail(res,409,"Refund cannot be rejected");await db.collection("refunds").updateOne({_id:refund._id},{$set:{status:"REJECTED",rejectedBy:u.id,rejectedAt:new Date(),updatedAt:new Date()}});return res.json({success:true,status:"REJECTED"});}if(action==="APPROVE"){if(refund.status!=="REQUESTED")return fail(res,409,"Refund is not awaiting approval");await db.collection("refunds").updateOne({_id:refund._id},{$set:{status:"APPROVED",approvedBy:u.id,approvedAt:new Date(),updatedAt:new Date()}});return res.json({success:true,status:"APPROVED"});}if(action!=="PROCESS"||refund.status!=="APPROVED")return fail(res,409,"Refund must be approved before processing");const payment=await db.collection("payments").findOne({id:refund.paymentId,status:"CAPTURED",providerPaymentId:{$exists:true}});if(!payment)return fail(res,409,"Captured payment not found");const provider=await razorpay(`/payments/${encodeURIComponent(payment.providerPaymentId)}/refund`,{method:"POST",body:JSON.stringify({amount:Number(refund.amountPaise),speed:"normal",receipt:String(refund.id).slice(0,40)})});const now=new Date();await db.collection("refunds").updateOne({_id:refund._id,status:"APPROVED"},{$set:{status:"COMPLETED",providerRefundId:provider.id,providerStatus:provider.status,processedBy:u.id,completedAt:now,updatedAt:now}});await db.collection("payments").updateOne({_id:payment._id},{$inc:{refundedAmountPaise:Number(refund.amountPaise)},$set:{updatedAt:now}});await writeAuditLog({actorId:u.id,actorRole:u.role,action:"FNB_REFUND_COMPLETED",entityType:"refund",entityId:refund.id,metadata:{fnbOrderId:refund.fnbOrderId,amountPaise:refund.amountPaise,providerRefundId:provider.id}});return res.json({success:true,status:"COMPLETED",providerRefund:{id:provider.id,status:provider.status,amount:provider.amount}});}

export async function handleAdminFnbCreditNote(req:Request,res:Response){const u=actor(req);if(!u||!["ADMIN","SUPER_ADMIN"].includes(String(u.role)))return fail(res,403,"Admin access required");const id=String(req.params.id||"").trim(),db=await getMongoDb(),refund=await db.collection("refunds").findOne({$or:[{id},...(ObjectId.isValid(id)?[{_id:new ObjectId(id)}]:[])]});if(!refund||!refund.fnbOrderId)return fail(res,404,"F&B refund not found");if(refund.status!=="COMPLETED")return fail(res,409,"Credit note requires a completed refund");const existing=await db.collection("credit_notes").findOne({refundId:refund.id});if(existing)return res.json({success:true,creditNote:existing,duplicate:true});const now=new Date(),note={id:makeId("CN"),creditNoteNumber:`CN-${now.getFullYear()}-${crypto.randomBytes(5).toString("hex").toUpperCase()}`,refundId:refund.id,fnbOrderId:refund.fnbOrderId,customerId:refund.customerId,amountPaise:refund.amountPaise,currency:"INR",reason:refund.reason,status:"ISSUED",issuedAt:now,immutable:true,createdAt:now};await db.collection("credit_notes").insertOne(note);await writeAuditLog({actorId:u.id,actorRole:u.role,action:"FNB_CREDIT_NOTE_ISSUED",entityType:"credit_note",entityId:note.id,metadata:{refundId:refund.id,amountPaise:refund.amountPaise}});return res.status(201).json({success:true,creditNote:note});}
