import crypto from "node:crypto";
import type { Request, Response } from "express";
import { getMongoDb } from "../server/mongodb.js";
import { writeAuditLog } from "../server/domainRepositories.js";
import type { AuthenticatedRequest } from "../server/auth.js";
const fail=(res:Response,status:number,error:string)=>res.status(status).json({success:false,error});
const admin=(req:Request)=>{const u=(req as AuthenticatedRequest).user;return u&&["ADMIN","SUPER_ADMIN"].includes(String(u.role))?u:null};
const clean=(v:unknown,max=1000)=>String(v??"").trim().slice(0,max); const bool=(v:unknown)=>[true,1,"1","true","TRUE","yes","YES","visible","VISIBLE"].includes(v as any); const slug=(v:string)=>v.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120);
function parseCsv(input:string){const lines=input.replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const parse=(line:string)=>{const out:string[]=[];let cur="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){out.push(cur);cur="";continue}cur+=c}out.push(cur);return out.map(x=>x.trim())};const h=parse(lines[0]).map(x=>x.toLowerCase().replace(/\s+/g,""));return lines.slice(1).map(line=>{const v=parse(line),r:any={};h.forEach((k,i)=>r[k]=v[i]??"");return r})}
async function applyRows(req:Request,rows:any[],source:string){const db=await getMongoDb(),games=db.collection("games"),media=db.collection("game_media"),now=new Date();let upserted=0,hidden=0,skipped=0,mediaUpserted=0;for(const raw of rows){const title=clean(raw?.title||raw?.name,180);if(!title){skipped++;continue}const category=clean(raw?.category||raw?.platform||"PS5",50),s=clean(raw?.slug,120)||slug(`${category}-${title}`);if(!s){skipped++;continue}const visible=bool(raw?.isvisible??raw?.isVisible??raw?.visible??raw?.status),gameId=clean(raw?.id,120)||`GAME-${s}`;await games.updateOne({slug:s},{$set:{id:gameId,slug:s,title,description:clean(raw?.description,2000),shortDescription:clean(raw?.shortdescription,500),category,isVisible:visible,sheetRow:raw?.sheetrow??null,sheetSource:source,updatedAt:now},$setOnInsert:{createdAt:now}},{upsert:true});upserted++;if(!visible)hidden++;const cover=clean(raw?.coverphoto||raw?.coverPhoto||raw?.coverimage||raw?.coverurl),photos=[raw?.image1,raw?.image2,raw?.image3,raw?.image4,raw?.image5].map(x=>clean(x)).filter(Boolean),video=clean(raw?.video||raw?.videourl||raw?.referencevideo);if(cover||photos.length||video)await media.updateOne({gameId},{$set:{gameId,slug:s,coverImage:cover||null,images:photos.slice(0,5),referenceVideo:video||null,updatedAt:now},$setOnInsert:{id:`MEDIA-${s}`,createdAt:now}},{upsert:true}),mediaUpserted++}const u=(req as AuthenticatedRequest).user;await writeAuditLog({actorId:u?.id||"GOOGLE_SHEETS",actorRole:u?.role||"INTEGRATION",action:"GOOGLE_SHEETS_GAME_SYNC",entityType:"games",entityId:"bulk",metadata:{source,rows:rows.length,upserted,hidden,skipped,mediaUpserted}});return{rows:rows.length,upserted,hidden,skipped,mediaUpserted,syncedAt:now.toISOString()}}
export async function handleGoogleSheetsSync(req:Request,res:Response){const secret=process.env.GOOGLE_SHEETS_WEBHOOK_SECRET?.trim();const supplied=String(req.header("x-google-sheets-secret")||req.header("x-webhook-secret")||"");if(!secret)return fail(res,503,"Google Sheets webhook secret is not configured");if(supplied.length!==secret.length||!crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(secret)))return fail(res,401,"Invalid sync secret");const rows=Array.isArray(req.body?.rows)?req.body.rows:Array.isArray(req.body)?req.body:[];if(rows.length>5000)return fail(res,400,"Maximum 5,000 rows per sync");return res.json({success:true,data:await applyRows(req,rows,String(req.body?.spreadsheetId||process.env.GOOGLE_SHEETS_SPREADSHEET_ID||"webhook"))})}
export async function handleGoogleSheetsPull(req:Request,res:Response){const u=admin(req);if(!u)return fail(res,403,"Admin access required");const url=process.env.GOOGLE_SHEETS_WEBHOOK_URL?.trim();if(!url)return fail(res,503,"GOOGLE_SHEETS_WEBHOOK_URL is not configured");try{const r=await fetch(url,{headers:{Accept:"application/json,text/csv","X-Google-Sheets-Secret":process.env.GOOGLE_SHEETS_WEBHOOK_SECRET||""}});if(!r.ok)return fail(res,502,"Google Sheets source request failed");const type=r.headers.get("content-type")||"",body=await r.text();let rows:any[]=[];if(type.includes("json")){const parsed=JSON.parse(body);rows=Array.isArray(parsed)?parsed:Array.isArray(parsed.rows)?parsed.rows:Array.isArray(parsed.data)?parsed.data:[]}else rows=parseCsv(body);if(rows.length>5000)return fail(res,400,"Maximum 5,000 rows per sync");return res.json({success:true,data:await applyRows(req,rows,"pull")})}catch{return fail(res,502,"Unable to pull Google Sheets catalog")}}
export async function handleGoogleSheetsStatus(req:Request,res:Response){const u=admin(req);if(!u)return fail(res,403,"Admin access required");const db=await getMongoDb();const [games,media]=await Promise.all([db.collection("games").countDocuments(),db.collection("game_media").countDocuments()]);return res.json({success:true,data:{configured:Boolean(process.env.GOOGLE_SHEETS_WEBHOOK_URL&&process.env.GOOGLE_SHEETS_WEBHOOK_SECRET),spreadsheetIdConfigured:Boolean(process.env.GOOGLE_SHEETS_SPREADSHEET_ID),games,media,lastSync:await db.collection("audit_logs").findOne({action:"GOOGLE_SHEETS_GAME_SYNC"},{sort:{createdAt:-1}})}})}
