import React, { useMemo, useState } from 'react';
import { Mail, Phone, Search, ShieldCheck, UserRound, UsersRound } from 'lucide-react';

type Account = { id: string; name: string; gamerTag?: string; email?: string; phone?: string; role?: string; createdAt?: string; isEmailVerified?: boolean; isWhatsappVerified?: boolean };

export const AdminAccountDirectory: React.FC<{ accounts?: Account[] }> = ({ accounts = [] }) => {
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return accounts; return accounts.filter(a => [a.name, a.gamerTag, a.email, a.phone, a.role].some(v => String(v || '').toLowerCase().includes(q))); }, [accounts, query]);
  return <div className="space-y-5 text-white">
    <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="mb-1 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.25em] text-red-400"><UsersRound className="h-4 w-4" /> Account directory</div><h2 className="text-2xl font-black">Players & staff</h2><p className="mt-1 text-xs text-white/40">Identity and verification data only. Passwords are never displayed or exported.</p></div><div className="relative w-full md:w-80"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white/25" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name, tag, email…" className="h-11 w-full rounded-xl border border-white/10 bg-white/[.04] pl-10 pr-4 text-sm outline-none focus:border-red-500/50" /></div></div>
    <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.02]"><div className="grid grid-cols-[1.4fr_1fr_1fr_.7fr] gap-4 border-b border-white/10 px-5 py-3 text-[9px] font-black uppercase tracking-wider text-white/30"><span>Account</span><span>Contact</span><span>Verification</span><span>Role</span></div>{filtered.length === 0 ? <div className="p-10 text-center text-sm text-white/35"><UserRound className="mx-auto mb-3 h-8 w-8 opacity-30" />No accounts found</div> : filtered.map(a => <div key={a.id} className="grid grid-cols-[1.4fr_1fr_1fr_.7fr] gap-4 border-b border-white/5 px-5 py-4 last:border-0"><div className="min-w-0"><div className="truncate text-sm font-bold">{a.name || 'Unnamed player'}</div><div className="mt-1 truncate text-xs text-red-400/80">{a.gamerTag || 'No GamerTag'}</div></div><div className="min-w-0 space-y-1 text-[11px] text-white/45"><div className="flex items-center gap-2 truncate"><Mail className="h-3 w-3" />{a.email || '—'}</div><div className="flex items-center gap-2 truncate"><Phone className="h-3 w-3" />{a.phone || '—'}</div></div><div className="space-y-1 text-[10px]"><div className="flex items-center gap-2 text-white/45"><ShieldCheck className="h-3 w-3 text-emerald-400" /> Email {a.isEmailVerified ? 'verified' : 'pending'}</div><div className="text-white/35">WhatsApp {a.isWhatsappVerified ? 'verified' : 'pending'}</div></div><div className="text-[10px] font-bold uppercase text-white/45">{a.role || 'CUSTOMER'}</div></div>)}</div>
  </div>;
};
