import React, { useState, useMemo } from 'react';
import { useCafe } from '../context/CafeContext';
import { GamingServiceCategory, GamingSystem } from '../types';
import { getGamesForCategory, getGamesForStation, ConsoleGameItem } from '../data/consoleGamesData';
import { GameDetailView } from './GameDetailView';
import { X, Search, Gamepad2, Monitor, Tv, Crown, Gauge, Glasses, CircleDot, Sparkles, ArrowRight, Wifi, Activity } from 'lucide-react';

interface ConsoleGamesModalProps { category: GamingServiceCategory; initialStationId?: string; onClose: () => void; onBookStation: (category: GamingServiceCategory, systemId?: string, gameTitle?: string) => void; }

export const ConsoleGamesModal: React.FC<ConsoleGamesModalProps> = ({ category, initialStationId, onClose, onBookStation }) => {
  const { systems, setSelectedStationForBooking, setSelectedGameForBooking, getRateForService, requireLogin } = useCafe();
  const safeSystems = Array.isArray(systems) ? systems.filter(Boolean) : [];
  const [selectedStationId, setSelectedStationId] = useState<string>(initialStationId || 'ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedGenre, setSelectedGenre] = useState('ALL');
  const [selectedGameForDetails, setSelectedGameForDetails] = useState<ConsoleGameItem | null>(null);
  const isTargetCategory = (sysCat: GamingServiceCategory) => sysCat === category || (category === 'PS5' && sysCat === 'PlayStation') || (category === 'PlayStation' && sysCat === 'PS5');
  const systemsInCategory = useMemo(() => safeSystems.filter(s => isTargetCategory(s.category)), [safeSystems, category]);
  const activeSystem = useMemo(() => selectedStationId === 'ALL' ? null : systemsInCategory.find(s => s.id === selectedStationId) || null, [selectedStationId, systemsInCategory]);
  const categoryGamesData = useMemo(() => {
    const result = getGamesForCategory(category, safeSystems);
    return Array.isArray(result) ? result : [];
  }, [category, safeSystems]);
  const allGenres = useMemo(() => ['ALL', ...Array.from(new Set(categoryGamesData.map(({game}) => String(game?.category || 'Other'))))], [categoryGamesData]);
  const filteredGames = useMemo(() => categoryGamesData.filter(({ game, installedStations }) => {
    const safeGame = game || ({} as ConsoleGameItem); const safeInstalled = Array.isArray(installedStations) ? installedStations : [];
    if (selectedStationId !== 'ALL' && !safeInstalled.some(s => s?.id === selectedStationId)) return false;
    if (selectedGenre !== 'ALL' && String(safeGame.category || '') !== selectedGenre) return false;
    if (searchQuery.trim()) { const q=searchQuery.toLowerCase(); const title=String(safeGame.title||'').toLowerCase(); const cat=String(safeGame.category||'').toLowerCase(); const tags=Array.isArray(safeGame.tags)?safeGame.tags:[]; const desc=String(safeGame.description||'').toLowerCase(); if(!title.includes(q)&&!cat.includes(q)&&!tags.some(t=>String(t).toLowerCase().includes(q))&&!desc.includes(q)) return false; }
    return true;
  }), [categoryGamesData, selectedStationId, selectedGenre, searchQuery]);
  const getCategoryConfig = (cat: GamingServiceCategory) => { switch(cat){case 'PS5':case 'PlayStation':return {title:'PlayStation 5 Console',subtitle:'Sony Bravia 4K 120Hz OLED • DualSense Edge',accent:'text-red-500',badgeBg:'bg-red-500/10 text-red-400 border-red-500/20',icon:<Gamepad2 className="w-5 h-5 text-red-500"/>};case 'Xbox':return {title:'Xbox Series X Console',subtitle:'Xbox Game Pass Ultimate • Elite Series 2',accent:'text-emerald-400',badgeBg:'bg-emerald-500/10 text-emerald-300 border-emerald-500/20',icon:<Gamepad2 className="w-5 h-5 text-emerald-400"/>};case 'PS4':return {title:'PlayStation 4 Pro / Slim',subtitle:'DualShock 4 • 50" HDR Gaming Displays',accent:'text-indigo-400',badgeBg:'bg-indigo-500/10 text-indigo-300 border-indigo-500/20',icon:<Tv className="w-5 h-5 text-indigo-400"/>};case 'Gaming PC':return {title:'Gaming PC Battle Rigs',subtitle:'Intel Core i9 14900K • RTX 4090 24GB • 240Hz OLED',accent:'text-cyan-400',badgeBg:'bg-cyan-500/10 text-cyan-300 border-cyan-500/20',icon:<Monitor className="w-5 h-5 text-cyan-400"/>};case 'Sim Racing':return {title:'Direct Drive Sim Racing Rigs',subtitle:'Fanatec DD2 25Nm • Triple Curved Displays • Hydraulic Pedals',accent:'text-orange-400',badgeBg:'bg-orange-500/10 text-orange-300 border-orange-500/20',icon:<Gauge className="w-5 h-5 text-orange-400"/>};case 'VR':return {title:'VR Motion Holodeck',subtitle:'Meta Quest 3 & Vive Pro 2 • 4x4m Padded 6DoF Play Area',accent:'text-teal-400',badgeBg:'bg-teal-500/10 text-teal-300 border-teal-500/20',icon:<Glasses className="w-5 h-5 text-teal-400"/>};case 'VIP Room':return {title:'VIP Gaming Lounge Suite',subtitle:'Private 8K Suite • Dual Liquid Cooled Rigs + PS5 • Dolby Atmos',accent:'text-purple-400',badgeBg:'bg-purple-500/10 text-purple-300 border-purple-500/20',icon:<Crown className="w-5 h-5 text-purple-400"/>};case 'Pool Table':return {title:'Championship Pool Tables',subtitle:'9ft Tournament Slate • Aramith Pro TV Balls • Predator Cues',accent:'text-yellow-400',badgeBg:'bg-yellow-500/10 text-yellow-300 border-yellow-500/20',icon:<CircleDot className="w-5 h-5 text-yellow-400"/>};default:return {title:`${category} Station`,subtitle:'High-Performance Arena Hardware',accent:'text-white',badgeBg:'bg-white/10 text-white border-white/20',icon:<Monitor className="w-5 h-5 text-white"/>};} };
  const config=getCategoryConfig(category);
  return <div id="console-games-modal-overlay" className="fixed inset-0 z-50 bg-black/90 backdrop-blur-md flex items-center justify-center p-2 sm:p-4 overflow-y-auto" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div id="console-games-modal-content" className="relative w-full max-w-5xl bg-[#0a0a0a] border border-white/15 rounded-2xl sm:rounded-3xl p-2.5 sm:p-7 my-auto max-h-[96vh] flex flex-col text-white backdrop-blur-xl animate-in fade-in zoom-in-95">
  <button onClick={onClose} className="absolute top-2.5 right-2.5 sm:top-4 sm:right-6 w-8 h-8 sm:w-9 sm:h-9 rounded-full bg-white/10 border border-white/10 flex items-center justify-center text-white/70 z-20"><X className="w-4 h-4"/></button>
  {selectedGameForDetails ? <div className="overflow-y-auto pr-1 flex-1 py-2"><GameDetailView game={{id:String(selectedGameForDetails.id||''),title:String(selectedGameForDetails.title||'Game'),tagline:String(selectedGameForDetails.multiplayerType||'4K Next-Gen Gaming Experience'),category:String(selectedGameForDetails.category||category),tags:Array.isArray(selectedGameForDetails.tags)?selectedGameForDetails.tags:[],description:String(selectedGameForDetails.description||''),price:`₹${getRateForService(category)}/hr`,rating:String(selectedGameForDetails.rating||''),platforms:Array.isArray(selectedGameForDetails.platforms)?selectedGameForDetails.platforms:[],bannerUrl:selectedGameForDetails.bannerUrl||selectedGameForDetails.coverUrl,coverUrl:String(selectedGameForDetails.coverUrl||''),multiplayerType:String(selectedGameForDetails.multiplayerType||'')}} defaultPlatform={category} onBack={()=>setSelectedGameForDetails(null)} onBookSlot={(game,selectedPlat)=>{let targetSys=activeSystem;if(!targetSys||targetSys.status!=='AVAILABLE')targetSys=safeSystems.find(s=>s.category===selectedPlat&&s.status==='AVAILABLE')||systemsInCategory[0];if(targetSys)setSelectedStationForBooking(targetSys);setSelectedGameForBooking({title:String(game.title||'Game'),category:selectedPlat,coverUrl:game.coverUrl});onBookStation(selectedPlat,targetSys?.id,String(game.title||'Game'));}}/></div> : <><div className="pt-1 pb-3 border-b border-white/10 flex items-center overflow-x-auto pr-10"><div className="flex items-center gap-2 flex-nowrap"><span className="text-[10px] uppercase tracking-widest text-white/40 font-bold pl-1">Select Rig:</span><button onClick={()=>setSelectedStationId('ALL')} className={`px-3 py-1.5 rounded-xl text-xs font-bold uppercase border ${selectedStationId==='ALL'?'bg-white text-black':'bg-white/5 text-white/60'}`}>All {category} Rigs ({categoryGamesData.length} Games)</button>{systemsInCategory.map(s=>{const installedCount=Array.isArray(s.installedGames)?s.installedGames.length:0;return <button key={s.id} onClick={()=>setSelectedStationId(s.id)} className={`px-3 py-1.5 rounded-xl text-xs font-bold uppercase border flex items-center gap-2 ${selectedStationId===s.id?'bg-white text-black':'bg-white/5 text-white/70'}`}><span className={`w-1.5 h-1.5 rounded-full ${s.status==='AVAILABLE'?'bg-emerald-400':s.status==='ACTIVE'?'bg-red-500':'bg-amber-400'}`}/><span>{s.name}</span><span className="text-[10px] font-mono px-1.5 rounded bg-white/10">{installedCount}</span></button>;})}</div></div>
  {activeSystem&&<div className="mt-3 p-3 rounded-2xl bg-white/5 border border-white/10 flex justify-between gap-3 text-xs"><div><b>{activeSystem.name} • {activeSystem.category}</b><p className="text-white/60 text-[11px] mt-0.5">{activeSystem.specs}</p></div><div className="flex gap-4 text-white/70 font-mono text-[11px]"><span><Wifi className="inline w-3.5 h-3.5"/> {activeSystem.ping}ms</span><span><Activity className="inline w-3.5 h-3.5"/> {activeSystem.temp}°C</span><span>{activeSystem.status}</span></div></div>}
  <div className="my-3 flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/40"/><input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder={`Search games on this ${category}...`} className="w-full bg-white/5 border border-white/10 rounded-xl pl-9 pr-4 py-2 text-xs text-white"/></div><div className="flex items-center gap-1.5 overflow-x-auto">{allGenres.map(genre=><button key={genre} onClick={()=>setSelectedGenre(genre)} className={`px-2.5 py-1.5 rounded-lg text-[10px] uppercase font-bold border ${selectedGenre===genre?'bg-white text-black':'bg-white/5 text-white/50'}`}>{genre}</button>)}</div></div>
  <div className="flex-1 overflow-y-auto pr-1 min-h-[320px] max-h-[50vh]">{filteredGames.length===0?<div className="h-64 flex items-center justify-center text-white/50">No games found.</div>:<div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2.5 sm:gap-4 pb-4">{filteredGames.map(({game})=>{const safeGame=game||({} as ConsoleGameItem);return <div key={safeGame.id} onClick={()=>requireLogin(()=>setSelectedGameForDetails(safeGame),`Please log in to view ${safeGame.title||'this game'} info and book.`)} className="group rounded-xl bg-white/[0.03] border border-white/10 overflow-hidden p-2 cursor-pointer"><div className="relative w-full aspect-[16/10] rounded-lg overflow-hidden bg-neutral-900 mb-2"><img src={safeGame.coverUrl||'/favicon.ico'} alt={String(safeGame.title||'Game')} className="w-full h-full object-cover" loading="lazy" referrerPolicy="no-referrer"/></div><h4 className="text-xs sm:text-sm font-bold text-white uppercase line-clamp-1">{String(safeGame.title||'Game')}</h4></div>;})}</div>}</div>
  <div className="pt-4 mt-2 border-t border-white/10 flex flex-col sm:flex-row items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-white/60"><Sparkles className="w-4 h-4"/><span>All games pre-installed with zero waiting time.</span></div><div className="flex gap-2 w-full sm:w-auto"><button onClick={onClose} className="flex-1 px-4 py-2.5 rounded-xl border border-white/15 text-xs font-bold">Back</button><button onClick={()=>requireLogin(()=>{let targetSys=activeSystem;if(!targetSys||targetSys.status!=='AVAILABLE')targetSys=systemsInCategory.find(s=>s.status==='AVAILABLE')||systemsInCategory[0];if(targetSys)setSelectedStationForBooking(targetSys);onBookStation(category,targetSys?.id);},`Please log in to reserve ${activeSystem?.name||config.title}.`)} className="flex-1 bg-red-600 text-white text-xs font-black px-6 py-2.5 rounded-xl flex items-center justify-center gap-2"><span>Reserve {activeSystem?.name||config.title}</span><ArrowRight className="w-4 h-4"/></button></div></div>
  </>}</div></div>;
};
